== Selección del Diario de George Fox

Para que todos conozcan los tratos del Señor conmigo, y los varios ejercicios,
pruebas y dificultades por las que Él me guió,
a fin de prepararme y ponerme en condiciones para la obra que Él había designado para mí,
y que de este modo,
se sientan atraídos a admirar y glorificar Su infinita sabiduría y bondad,
creo adecuado mencionar brevemente (antes de proceder a
exponer mis viajes públicos en el servicio de la Verdad),
qué paso conmigo en mi juventud, cómo empezó la obra del Señor,
y cómo fue llevada a cabo gradualmente en mí, desde mi niñez.

Nací en el mes llamado Julio del año 1624, en Drayton-in-the-clay, Leicestershire.
El nombre de mi padre era Christopher Fox.
Era tejedor de oficio,
un hombre honesto y que tenía la semilla de Dios en él. Sus vecinos
lo llamaban '`Christer el justo.`' Mi madre era una mujer recta;
su nombre de soltera era María Lago, de la familia de los Lago,
y del linaje de los mártires.

En mis primeros años yo tenía una seriedad y firmeza de
mente y espíritu que no son habituales en los niños,
al punto,
que cuando yo veía a los hombres mayores comportarse
con ligereza y licenciosamente entre ellos,
sentía que se levantaba un disgusto en mi corazón y me decía en el interior:
"`Si alguna vez llego a ser un hombre, de seguro no seré así,
ni seré tan libertino y descuidado.`"

Cuando llegué a los once años, conocía la pureza y la justicia,
pues siendo todavía un niño, fui enseñado a caminar de manera que me mantuviera puro.
El Señor me enseñó a ser fiel en todas las cosas y a actuar fielmente en dos formas:
Tanto internamente para Dios y externamente para el hombre,
como a mantener el "`sí`" y el "`no`" en todas las cosas.
Porque el Señor me mostró,
que aunque la gente del mundo tuviera bocas llenas de engaño y palabras cambiantes,
yo debía mantener el "`sí`" y el "`no`" en todas las cosas,
y que mis palabras debían ser pocas y con sal, sazonadas con gracia.
Vi que no debía comer ni beber en exceso, únicamente por salud,
usando las cosas creadas en su servicio apropiado, como siervas en sus lugares,
para gloria de Aquel que las creó--ellas en su pacto,
y yo siendo introducido en el pacto y santificado por la Palabra que estaba en el principio,
por medio de la cual todas las cosas son sustentadas,
y en la que hay unidad con la creación.

Pero las personas que son ajenas al pacto de vida con Dios, comen y beben sin freno,
desperdiciando las cosas creadas en sus propios deseos, y viviendo en toda inmundicia,
amando los caminos viles y devorando la creación. Vi que
todo eso está en el mundo y en sus contaminaciones,
separado de Dios; por tanto, yo debía evitar todas esas cosas.

Después, a medida que crecía, mi familia pensaba hacerme sacerdote,
pero otros los persuadían de lo contrario,
tras lo cual fui puesto como aprendiz de un hombre, zapatero de oficio,
que también comerciaba con lana; era granjero y vendía ganado,
y una gran cantidad de bienes pasaban por mis manos.
Mientras estuve con ese hombre, fue bendecido, pero después de que lo dejé,
quebró y quedó en nada.
En todo ese tiempo nunca perjudiqué a nadie,
hombre o mujer, porque el poder del Señor estaba conmigo y sobre mí para preservarme.
Mientras estaba en ese servicio,
usaba las palabras "`en verdad`" en mis tratos con los hombres,
y era un dicho común entre la gente que me conocía:
"`Si George dice '`en verdad,`' no hay forma de hacerlo cambiar.`"
Cuando los muchachos y las personas groseras se reían de mí,
los dejaba solos y seguía mi camino, pero en general,
la gente me amaba por mi inocencia y honestidad.

Cuando estaba por llegar a los diecinueve años, estando en negocios en una feria,
uno de mis primos (cuyo nombre era Bradford), profesante^
footnote:[La palabra _profesante_ es usada a lo largo
de los escritos de los primeros Amigos,
para referirse a los que _profesan_ fe en Cristo.]
del cristianismo, acompañado de otro profesante,
vino a mí y me pidió que tomara con ellos parte de una jarra de cerveza.^
footnote:[En aquellos días todo el mundo bebía cerveza, incluso los niños,
porque el agua generalmente no estaba limpia.]
Puesto que tenía sed, fui con ellos,
porque amaba a cualquiera que tuviera un deseo por el bien,
o que buscara al Señor. Cuando cada uno de nosotros se había tomado un vaso,
ellos comenzaron a hacer brindis,^
footnote:[Tomar a la salud u honor de otro.]
pidieron más cerveza y acordaron que el que no tomara debía pagarlo todo.
Me afligió que alguien que hacía profesión de religión actuara de esa manera.
De hecho, ellos me entristecieron mucho,
pues ningún tipo de cristiano me había sugerido algo así antes.
Por tanto, me levanté para irme, y metiendo mi mano en el bolsillo,
saqué una moneda de plata, la puse delante de ellos y les dije: "`Si va a ser así,
yo los dejo.`"
En seguida me fui, y cuando había terminado el negocio que tenía que hacer,
regresé a casa, pero esa noche no me acosté, ni pude dormir,
sino que a ratos caminaba de un lado a otro, y a ratos oraba y clamaba al Señor,
quien entonces me dijo:
"`Tú ves que los jóvenes van tras la vanidad y los mayores tras lo terrenal,
pero tú debes abandonar a todos, tanto a jóvenes como a mayores,
mantenerte alejado de todos y ser un extraño para todos.`"

Y así, por mandato de Dios, el noveno día del séptimo mes de 1643, dejé a mi familia,
y rompí toda cercanía o compañerismo con jóvenes y viejos.
Me fui a Lutterworth, donde estuve un tiempo, y de ahí a Northampton,
donde también me quedé un tiempo.
De ahí me fui a Newport Pagnell, donde,
después de haberme quedado por un tiempo me fui a Barnet, el cuarto mes llamado Junio,^
footnote:[Hasta 1752,
Marzo fue considerado el primer mes del año en toda Inglaterra y sus colonias.]
de 1644.
Mientras viajaba por el país, los profesantes se fijaron en mí y buscaban conocerme,
pero yo tenía temor de ellos, porque era consciente de que no poseían lo que profesaban.

Durante el tiempo que estuve en Barnet,
vino sobre mí una fuerte tentación de desesperación.
Entonces vi cómo había sido tentado Cristo,
y me vi en gran angustia.
A veces me mantenía retirado en mi alcoba, y a menudo caminaba solo a campo abierto,
para esperar en el Señor. Me preguntaba por qué estas cosas estaban sobre mí,
y me miraba a mí mismo y me decía: "`¿He estado así alguna vez antes?`"
Entonces pensaba que tal vez,
por haber abandonado a mi familia había hecho mal contra ellos;
esto me llevaba a recordar todo el tiempo que había pasado así,
y a considerar si yo había perjudicado a alguien.
Pero las tentaciones seguían creciendo,
y era tentado casi hasta la desesperación. Y cuando Satanás
no pudo efectuar su designio sobre mí de esa manera,
me puso trampas y cebos para arrastrarme a cometer algún pecado
con el que pudiera aprovecharse y llevarme a la desesperación.
Yo tenía unos veinte años cuando me sobrevinieron estas pruebas,
y continué en esa condición por algunos años más, en gran aflicción,
y deseando ansiosamente quitarla de mí. Acudí a muchos sacerdotes en busca de consuelo,
pero no lo encontré.

De Barnet fui a Londres,
donde tomé un alojamiento y estuve bajo gran miseria y angustia allí;
pues observando a los grandes profesantes cristianos de la ciudad,
vi que todos estaban en oscuridad y bajo cadenas de tinieblas.
Yo tenía ahí un tío llamado Pickering,
que era Bautista (que entonces eran personas tiernas),
pero no pude abrirle mi mente a él, ni unirme a ellos, porque vi donde estaban todos;
jóvenes y viejos.
Algunas personas tiernas querían que me quedara,
pero yo tenía miedo y regresé a mi casa en Leicestershire,
en consideración a mis padres y familiares, para no entristecerlos,
pues según entendía yo, estaban preocupados por mi ausencia.

Cuando llegué a Leicestershire, mi familia quería que me casara,
pero les dije que yo no era más que un muchacho,
y que debía adquirir sabiduría. Otros querían que
me uniera al grupo auxiliar entre los soldados,
pero me negué, y me entristeció que ellos me propusieran esas cosas,
siendo un joven tierno.
Entonces me fui a Coventry,
donde por un tiempo tomé una habitación en la casa de un profesante,
hasta que la gente empezó a conocerme; pues había mucha gente tierna en ese pueblo.
Después de un tiempo regresé a mi propio condado,
y estuve ahí aproximadamente un año bajo grandes penas y tribulaciones,
y muchas noches salía a caminar solo.

El sacerdote de Drayton, el pueblo donde nací, cuyo nombre era Natanael Stevens,
a menudo me visitaba y yo a él, y a veces lo acompañaba otro sacerdote.
Ellos daban lugar para escucharme, y yo les hacía preguntas y razonaba con ellos.
Este sacerdote Stevens, una vez me preguntó por qué Cristo había clamado en la cruz:
"`Dios mío, Dios mío, ¿por qué me has desamparado?`"
Y por qué había dicho: "`Si es posible, pase de mí esta copa; pero no sea como yo quiero,
sino como tú.`" Yo le dije que en ese momento los
pecados de toda la humanidad estaban sobre Él,
las iniquidades y transgresiones de todos los hombres con las que estaba siendo herido,
las cuales debía llevar, y por las que debía ser una ofrenda, como hombre,
pero que Él no había muerto como Dios.
Y que así, al morir por todos los hombres y probar la muerte por cada uno,
había sido una ofrenda por los pecados de todo el mundo.
Eso lo dije en ese momento,
estando en cierta medida consciente de los sufrimientos de Cristo,
y de lo que Él había atravesado.
El sacerdote dijo que era una respuesta muy buena y completa,
y una que no había escuchado.
En ese tiempo, él me aprobaba y les hablaba a los demás muy bien de mí;
y de lo que yo le decía en conversaciones durante la semana,
él predicaba los Primeros-días, por lo que no me caía bien.
Este sacerdote luego se convirtió en un gran perseguidor.

Después de esto fui a ver a otro anciano sacerdote en Mancetter, en Warwickshire,
y razoné con él acerca del motivo de la desesperación y de las tentaciones,
pero como él desconocía mi condición,
me dijo que fumara un poco de tabaco y cantara salmos.
El tabaco era algo que no me gustaba, y yo no estaba en condiciones de cantar salmos;
en realidad, no podía cantar.
Él me dijo que regresara y que entonces me diría muchas cosas,
pero cuando regresé estaba enojado y malhumorado,
porque mis palabras anteriores le habían disgustado.
Él le había contado mis dificultades, tristezas y aflicciones a sus sirvientes,
y me afligió haberle abierto mi mente a ese hombre.
Vi que todos ellos eran "`consoladores molestos,`"^
footnote:[Job 16:2]
y esto trajo más angustia sobre mí.

Luego oí de un sacerdote que vivía cerca de Tamworth,
quien era considerado un hombre de experiencia, y caminé siete millas para verlo,
pero descubrí que era como un barril vacío y hueco.
También oí de un hombre llamado Dr. Cradock, de Coventry, y fui a verlo.
Le pregunté el motivo de las tentaciones y de la desesperación,
y cómo se formaban las tribulaciones en el hombre.
Él me preguntó: "`¿Quiénes eran el padre y la madre de Cristo?`"
Yo le respondí que María era la madre de Él, y que se creía que era hijo de José,
pero que Él era el Hijo de Dios.
Entonces, mientras caminábamos juntos en su jardín y estrecharse el sendero,
me volví e involuntariamente puse mi pie al lado de una '`cama de flores,`' ante lo cual,
este hombre se enfureció como si su casa estuviera ardiendo en llamas.
En ese momento se perdió toda nuestra conversación y me fui entristecido,
sintiéndome peor que como había llegado.
Consideré que ellos eran "`consoladores molestos,`"
y vi que todos eran como nada para mí,
porque no podían alcanzar mi condición.

Después de eso fui a ver a un sacerdote de gran estima llamado Macham.
Él quería darme medicinas y sangrarme, pero no me pudo sacar una gota de sangre,
ni de mis brazos, ni de mi cabeza (aunque se esforzó por hacerlo), ya que mi cuerpo,
por decirlo así, estaba seco de tristezas, aflicciones y dificultades,
las cuales eran tan grandes, que deseaba no haber nacido nunca, o haber nacido ciego,
para nunca haber visto la maldad y la vanidad, o sordo,
para nunca haber oído palabras vanas y malvadas, o el nombre del Señor blasfemado.
Y cuando llegaba el tiempo llamado Navidad, mientras otros festejaban y se divertían,
yo buscaba a las viudas pobres de casa en casa y les daba algo de dinero.
Y cuando me invitaban a matrimonios (como sucedió en algunas ocasiones),
no iba a ninguno, pero al día siguiente, o poco después,
visitaba a los recién casados y si eran pobres, les daba algo de dinero.
Pues yo tenía suficiente, tanto para evitar ser carga para otros,
como para proveer algo para las necesidades de aquellos que estaban en necesidad.

A comienzos del año 1646, mientras iba hacia Coventry y me aproximaba a la puerta,
se levantó un pensamiento en mí acerca de la creencia que decía:
"`Todos los cristianos son creyentes, tanto protestantes como católicos.`"
El Señor me reveló que sólo eran creyentes los que habían
nacido de Dios y habían pasado de muerte a vida,
y que nadie era verdadero creyente sino estos;
y que aunque muchos otros dijeran que eran creyentes, no lo eran.
En otro momento, mientras caminaba por un campo la mañana de un Primer-día,
el Señor me reveló que ser educado en Oxford o Cambridge,
no era suficiente para preparar y capacitar a los
hombres para que fueran ministros de Cristo;
esto me sorprendió, porque esa era la creencia común de la gente.
Pero cuando el Señor me lo reveló lo vi claramente, y quedé satisfecho,
y admiré la bondad del Señor que me había revelado eso aquella mañana.
Vi que eso golpeaba el ministerio del sacerdote Stevens,
pero como mi familia se angustiaba mucho porque yo no iba con ellos a escucharlo,
sino que prefería irme solo a los huertos o a los campos con mi Biblia, les pregunté:
"`¿Acaso no les dijo el apóstol a los creyentes,
que ellos no necesitaban ningún hombre que les enseñara,
porque la unción les enseñaba todas las cosas^
footnote:[1 Juan 2:27]?`" Y aunque ellos sabían que esa era una Escritura,
y que era cierta, aun así se dolían,
porque yo no me sujetaba en este asunto e iba a escuchar al sacerdote con ellos.
Yo había visto que ser un verdadero creyente era algo diferente de lo que ellos consideraban.
Y yo había visto que ser educado en Oxford o Cambridge no preparaba
o capacitaba a ningún hombre para que fuera ministro de Cristo.
Entonces, ¿por qué iba a seguir a tales hombres?
Por tanto, no podía unirme a estos, ni a ninguno de los disidentes,^
footnote:[Los disidentes eran personas cristianas, que por diversas razones,
no estaban de acuerdo con la religión del estado ni se conformaban a ella.]
sino que era un extraño para todos, y confiaba enteramente en el Señor Jesucristo.

En otro momento me fue revelado, que "`Dios que hizo el mundo,
no habita en templos hechos por manos.`"
Esto al principio me pareció extraño,
porque tanto los sacerdotes como la gente solían llamar a sus templos
o iglesias "`lugares terribles,`" "`tierra santa,`" "`templos de Dios.`"
Pero el Señor me mostró claramente,
que Él no habitaba en los templos que los hombres habían concebido y erigido,
sino en los corazones de las personas,
pues tanto Esteban como el apóstol Pablo habían dado testimonio
de que Él no habitaba en templos hechos por manos,
ni siquiera, en el templo que una vez había mandado a levantar,
dado que Él le había puesto fin; que Su pueblo era Su templo y que Él habitaba en ellos.
Esto me fue revelado mientras caminaba en los campos hacia la casa de mi familia.
Cuando llegué me dijeron que el sacerdote Natanael Stevens había estado ahí,
y que les había dicho que estaba preocupado por mí,
porque estaba caminando tras nuevas luces.
Yo sonreí para mis adentros,
sabiendo lo que el Señor me había revelado con respecto a él y sus hermanos,
pero no le dije nada de esto a mis parientes, quienes,
aunque veían más allá que los sacerdotes,
continuaban escuchándolos y se sentían afligidos porque yo no iba también. Sin embargo,
yo les mostraba Escrituras y les decía que había una unción dentro del hombre para enseñarle,
y que el Señor mismo le enseñaba a Su pueblo.

A pesar de que en ese entonces yo tenía grandes revelaciones,
con frecuencia me sobrevenían grandes aflicciones y tentaciones,
de modo que cuando era de día yo deseaba que fuera de noche,
y cuando era de noche deseaba que fuera de día. Debido
a las revelaciones que tenía en mis tribulaciones,
podía decir como David: "`Un día emite palabra a otro día,
y una noche a otra noche declara sabiduría.`"^
footnote:[Salmo 19:2]
Cuando tenía revelaciones, ellas se correspondían unas con otras,
y también se correspondían con las Escrituras;
porque yo tenía grandes revelaciones de las Escrituras; y cuando tenía aflicciones,
una aflicción también se correspondía con otra.

A principios del año 1647, me sentí movido por el Señor a ir a Derbyshire,
donde me encontré algunas personas amistosas con las que tuve muchas conversaciones.
Luego pasé al condado Peak y me encontré con más personas amables,
y con algunas que tenían ideas vacías y orgullosas.
Continué viajando por algunas partes de Leicestershire y Nottinghamshire,
y me encontré con personas de corazón bondadoso y con una
mujer muy tierna cuyo nombre era Elizabeth Hooton,^
footnote:[Elizabeth Hooton no sólo fue la primera mujer,
sino la segunda persona que apareció como ministro entre la recién reunida sociedad.
Ella no había testificado mucho tiempo públicamente como ministra,
antes de que su sinceridad y fidelidad fueran puestas a
prueba por la persecución. Además de sufrir de otras maneras,
en algunas ocasiones soportó varios encarcelamientos por meses seguidos.
Como ministra del evangelio fue muy estimada por sus amigos,
y a edad avanzada realizó dos visitas religiosas a América y a las islas del Caribe.]
con quienes tuve algunas reuniones y conversaciones.
Pero mis tribulaciones continuaban, y a menudo estaba bajo grandes tentaciones.
Yo ayunaba mucho y salía a caminar por lugares solitarios muchos días,
y con frecuencia cogía mi Biblia y me sentaba en árboles
huecos y lugares despoblados hasta que llegaba la noche.
Durante la noche, frecuentemente vagaba lleno de tristeza y solo,
pues yo era un hombre de dolores en los tiempos en
que el Señor obraba por primera vez en mí.

Durante todo ese tiempo nunca me uní en profesión religiosa a nadie,
sino que me entregué al Señor, tras haber abandonado toda mala compañía,
y haberme despedido de mi padre, madre y de todos mis otros parientes.
Viajé de arriba a abajo como un extraño en la tierra,
en cualquier dirección a la que el Señor inclinara mi corazón,
y tomaba una habitación para mí en el pueblo al que llegaba, quedándome a veces un mes,
más o menos, en un lugar.
Porque no me atrevía a quedarme mucho tiempo en un solo lugar,
porque le temía tanto a profesantes como a profanos, no fuera que al ser un joven tierno,
me lastimara conversar mucho con ellos.
Por esta razón me mantenía como un extraño,
buscando la sabiduría celestial y obteniendo conocimiento del Señor,
de esa manera era destetado de las cosas externas,
para confiar total y únicamente en el Señor.

Aunque mis pruebas y dificultades eran muy grandes,
no eran tan constantes como para no tener descansos,
pues algunas veces era llevado a tal gozo celestial
que pensaba que había estado en el seno de Abraham.
Y como no puedo hablar de la miseria en la que estaba,
que era muy grande y pesada sobre mí,
tampoco puedo exponer las misericordias de Dios hacia mí en toda mi miseria.
¡Oh, el amor eterno de Dios hacia mi alma, cuando me encontraba en gran angustia!
Cuando mis dificultades y tormentos eran grandes, entonces Su amor era sobremanera grande.
Tú, Señor, conviertes un campo fructífero en árido desierto,
y un árido desierto en campo fructífero.
Tú derribas y levantas; matas y haces vivir.
Todo el honor y la gloria sean para Ti, oh Señor de gloria;
porque el conocimiento de Ti en el Espíritu es vida,
pero el conocimiento que es carnal obra muerte.
Mientras exista este conocimiento en la carne,
la voluntad propia y el engaño se amoldarán a cualquier cosa, y el hombre le dirá "`sí,
sí`" a eso que no conoce.
El conocimiento que tiene el mundo de lo que los profetas y apóstoles hablaron,
es un conocimiento carnal,
y aquellos que han apostatado de esa vida en la que los profetas y apóstoles vivieron,
han aprendido sus palabras (las Sagradas Escrituras) de manera externa,
pero no en esa vida o Espíritu que las dio.
Y así, todos yacen en confusión, y hacen provisión para la carne,
para cumplir los deseos de esta; pero no cumplen la ley y mandamiento de Cristo,
en el poder y Espíritu de Cristo.
Dicen que no pueden hacer eso,
pero sí pueden satisfacer los deseos de la carne con deleite.

Después de que recibí la revelación del Señor de que ser educado en Oxford o Cambridge
no era suficiente para preparar a un hombre para que fuera ministro de Cristo,
yo estimaba menos a los sacerdotes y miraba más hacia los disidentes.
Entre ellos vi que había cierta ternura,
y después muchos de ellos fueron convencidos por la verdad,
pues tenían algunas revelaciones.
Pero así como había abandonado a los sacerdotes,
también dejé a los predicadores separados,
y a las personas que eran estimadas como las más experimentadas,
porque vi que ninguno de ellos podía decir una palabra sobre mi condición.
Cuando todas mis esperanzas en ellos y en todos los hombres habían desaparecido,
de modo que no tenía nada externo que me ayudara, ni pudiera decirme qué hacer, entonces,
¡oh, entonces!, oí una voz que dijo: "`¡Hay uno, Cristo Jesús,
que puede hablar sobre tu condición!;`" y cuando la oí,
mi corazón dio un salto de alegría. Entonces el Señor me dejó ver la razón
por la que nadie sobre la tierra podía hablar sobre mi condición,
a saber, para que yo le diera a Él toda la gloria;
porque todos están bajo pecado y encerrados en incredulidad, como yo había estado,
y de este modo Jesucristo tuviera la preeminencia, quien alumbra y da gracia, fe y poder.
Por tanto, cuando Dios obra, ¿quién le estorbará? Esto lo supe por experiencia.

Mis deseos en pos del Señor se hicieron más fuertes,
y creció mi celo por sólo conocer el conocimiento puro de Dios y de Cristo,
sin la ayuda de ningún hombre, libro o escritura.
Porque aunque yo leía las Escrituras que hablaban de Cristo y de Dios,
sólo Lo conocía por revelación, conforme se revelaba Aquel que tiene la llave,
y conforme el Padre de Vida me atraía a Su Hijo por medio de Su Espíritu.
Luego el Señor me guió suavemente y me dejó ver Su amor, el cual era infinito y eterno,
sobrepasando todo el conocimiento que tienen los hombre en su estado natural,
o el que pueden obtener de la historia o los libros; y ese amor me dejó verme a mí mismo,
tal como era sin Él.

Yo temía toda compañía, porque veía perfectamente donde estaban,
a través del amor de Dios que me había permitido verme a mí mismo.
Por tanto, no tenía comunión con ninguna persona, sacerdote o profesante,
ni con ningún tipo de persona separada, sino sólo con Cristo,
quien tiene la llave y abrió la puerta de Luz y Vida para
mí. Le temía a toda conversación y conversadores carnales,
porque no podía ver más que corrupciones y cómo yacía la vida bajo
la carga de corrupción. Cuando yo mismo estaba en las profundidades,
atrapado bajo todo, no podía creer que algún día vencería, porque mis dificultades,
mis tristezas y mis tentaciones eran tan grandes,
que muchas veces pensé que caía en la desesperación. Pero cuando
Cristo me reveló cómo había sido tentado por el mismo diablo,
y cómo lo había vencido y herido en la cabeza, y que a través de Él y de Su poder,
de Su luz, Su gracia y Espíritu, yo también podía vencer,
entonces confié en Él. Así que era Él quien '`me abría cuando
estaba cerrado`' y no tenía esperanza ni fe.
Cristo, quien me alumbraba, me daba Su luz para creer.
Me daba esperanza, la cual Él mismo revelaba en mí; me daba Su Espíritu y Su gracia,
la cual yo encontraba suficiente en las profundidades y debilidades.
Por tanto,
en las miserias más profundas y en las más grandes
tristezas y tentaciones que muchas veces me asaltaban,
el Señor en Su misericordia me guardaba.

Descubrí que había dos tipos de sed en mí: Una tras las cosas creadas,
que buscaba obtener ayuda y fuerza ahí; la otra, tras el Señor,
el Creador y Su Hijo Jesucristo.
Vi que nada del mundo podía hacerme bien, y que si hubiera tenido la dieta,
el palacio y los siervos de un rey, habría sido como nada, pues nada me daba consuelo,
sino el Señor por medio de Su poder.
Vi cómo los profesantes,
los sacerdotes y las personas se sentían completos
y tranquilos en la misma condición que era mi miseria,
y que ellos amaban eso de lo que yo anhelaba ser libre.
Pero el Señor mantenía mis deseos hacia Él, de quien venía mi ayuda,
y toda mi ansiedad fue echada sobre Él.

Por tanto, esperen pacientemente en el Señor,
cualquiera que sea la condición en que se encuentren;
esperen en la gracia y verdad que vienen por medio de Jesús. Porque si lo hacen,
hay una promesa para ustedes y el Señor Dios la cumplirá en ustedes.
¡Bienaventurados todos los que efectivamente tienen hambre y sed de justicia,
porque ellos serán saciados de ella!
Yo he descubierto que es así, alabado sea el Señor,
que llena de justicia y satisface los deseos del alma hambrienta! ¡Oh,
que la casa del Israel espiritual diga: "`Su misericordia es eterna!`"
Es una manifestación del amor de Dios,
cambiar en un árido desierto lo que es agradable para el ojo externo y la mente carnal,
y cambiar un árido desierto en un campo fructífero.
¡Esta es la gran obra de Dios!
Sin embargo, las mentes de las personas permanecerán en esclavitud,
mientras corran hacia lo terrenal, en pos de las cosas creadas y cambiantes,
hacia las formas y religiones cambiantes, y hacia los maestros inciertos y cambiantes;
porque entonces ellas mismas son cambiantes,
llevadas de aquí para allá por todo viento de doctrina,
pensamiento y conceptos de las cosas,
y sus mentes permanecen fuera de la inmutable verdad en lo íntimo--la
Luz de Jesucristo--la cual las mantendría atadas a lo que es inmutable.
Él es el camino al Padre,
y en todas mis dificultades Él me ha preservado por medio de Su Espíritu y poder.
¡Alabado sea Su santo nombre para siempre!

Nuevamente oí una voz que decía: "`¡Tú, serpiente! ¡Tú buscas destruir la vida,
pero no puedes, porque la espada que guarda el árbol de la vida te destruirá a ti!`"
Así Cristo, la Palabra de Dios que hirió la cabeza de la serpiente, el destructor,
me preservó; al unirse mi mente interior a Su buena Semilla,
a la que hiere la cabeza de esta serpiente, el destructor.
Esta vida interior brotó en mí y me permitió responderles
a todos los profesantes y sacerdotes que se oponían,
y traía a mi memoria Escrituras con las cuales refutarlos.

En otro momento vi el gran amor de Dios, y fui colmado de admiración ante su infinitud.
Vi lo que queda expulsado de Dios, y lo que puede entrar en el reino de Dios,
y cómo por medio de Jesús, el que abre la puerta con Su llave celestial,
se obtiene la entrada.
Vi la muerte,
cómo había pasado a todos los hombres y cómo oprimía a la Semilla de Dios
en el hombre y en mí. Pero vi cómo había salido yo en la Semilla,
y también vi a qué pertenecía la promesa de Dios.
Sin embargo, yo seguía en tal condición,
que parecía que había dos cosas abogando dentro de mí. Entonces
se levantaban en mi mente preguntas acerca de los dones y las profecías,
y era tentado de nuevo hasta la desesperación,
como si hubiera pecado contra el Espíritu Santo.
Permanecí en gran perplejidad y angustia por muchos días, sin embargo,
yo seguía rindiéndome al Señor.

Un día, después de que había salido a caminar solo, y había regresado a casa,
fui envuelto en el amor de Dios,
de modo que no pude evitar admirar la grandeza de Su amor.
Mientras estaba en ese estado, me fue mostrado por la luz y el poder eternos,
y entendí claramente por medio de ello, que "`todo fue hecho y debe ser hecho,
en y por Cristo.`"
Vi cómo conquista y destruye Él a este tentador, al Diablo y todas sus obras,
y que está sobre él; y que todas estas tribulaciones eran buenas para mí,
y que eran tentaciones para probar mi fe, la que Cristo me había dado.
El Señor abrió mis ojos, de modo que vi a través de todas esas angustias y tentaciones,
y mi fe viva fue incrementada; y vi cómo todo había sido hecho por Cristo, la vida,
y por tanto, mi confianza fue puesta en Él.

Cuando en algún momento mi condición era velada, mi confianza secreta permanecía firme,
y la esperanza debajo me sostenía como un ancla en el fondo del mar,
asegurando mi alma inmortal a su Obispo y haciéndola nadar sobre el mar, es decir,
el mundo--donde están todas las olas furiosas, el mal tiempo,
las tempestades y las tentaciones.
¡Pero, oh, entonces vi mis dificultades,
pruebas y tentaciones más claramente de lo que las había visto alguna vez!
Cuando la luz apareció, todo lo que estaba fuera de la luz apareció--tinieblas, muerte,
tentaciones, injusticia, impiedad--todo fue manifestado y visto en la luz.
Después de esto apareció en mí un fuego puro,
y vi cómo se sentaba Cristo "`como fuego purificador y como jabón de lavadores,`"^
footnote:[Malaquías 3:2]
y vino sobre mí, discernimiento espiritual,
por medio del cual pude discernir mis propios pensamientos, gemidos y suspiros,
y ver qué era eso que me cubría como un velo y qué era eso que me quitaba el velo.
En la luz descubrí, que eso que no podía permanecer en la paciencia ni soportar el fuego,
eran los gemidos de la carne, la cual no podía rendirse a la voluntad de Dios.
Era esto lo que me había cubierto tanto, que yo no podía ser paciente en las pruebas,
angustias y perplejidades,
y no podía rendir el yo a la muerte de la cruz (la cual es poder de Dios),
para que eso que está vivo y vivificado pudiera seguirlo a Él,
y eso que nublaba y velaba la presencia de Cristo (lo que la espada
de Cristo corta y debe morir) no pudiera mantenerse vivo.
También discerní los gemidos del Espíritu,
los cuales se abrían paso en mí y hacían intercesión ante Dios,
en cuyo Espíritu está la verdadera espera en Dios para la redención
del cuerpo y de toda la creación. Por medio de este Espíritu,
en el que se experimenta el verdadero suspiro,
vi más allá de todos los falsos suspiros y gemidos;
y también discerní por medio de este Espíritu invisible, el falso oír,
el falso ver y el falso oler,
que se había levantado en el hombre por encima del Espíritu,
apagándolo y entristeciéndolo.
Vi que todos los que vivían aquí estaban en confusión y engaño,
donde existen una falsa súplica y una falsa oración en esa naturaleza
y lengua que toma el santo nombre de Dios en vano,
se revuelca en el mar de Egipto y pide pero no recibe; pues ellos odian Su luz,
resisten al Espíritu Santo, vuelven la gracia en libertinaje,
se rebelan contra el Espíritu,
y se han desviado de la fe en la que deben pedir
y del Espíritu por medio del que deben orar.

El que conoce estas cosas en el verdadero Espíritu puede experimentarlas.
La luz divina de Cristo pone de manifiesto todas las cosas,
el fuego espiritual prueba todas las cosas y divide todas las cosas.
Luego vi varias cosas conforme el Señor me las revelaba,
pues Él me mostró lo que puede vivir en Su santo fuego refinador,
y lo que puede vivir para Dios bajo Su ley.
Él me hizo ver que la ley y los profetas habían sido hasta Juan,
y que el más pequeño en el reino eterno de Dios era mayor que Juan.
La ley pura y perfecta de Dios está sobre la carne,
para mantener la carne y sus obras (que no son perfectas) sometidas;
y la ley de Dios que es perfecta, está en concordancia con el don^
footnote:[Él se refiere a la medida de gracia,
luz o semilla del reino que está sembrada en los corazones de los hombres,
para salvar a todo el que la recibe y obedece.]
perfecto de Dios en cada uno.
Los judíos, los profetas y Juan debían cumplir y hacer esta ley.
Nadie conoce al Dador de esta ley sino por el Espíritu de Dios,
ni puede verdaderamente leerla o escuchar su voz sino por el Espíritu de Dios;
el que pueda recibir esto, que lo reciba.
Juan, quien fue el mayor profeta nacido de una mujer, dio testimonio de la luz,
con la que Cristo (el gran Profeta celestial) "`alumbra
a todo hombre que viene a este mundo^
footnote:[Juan 1:9 RVG,
RV 1602 P],`" para que crea en ella y llegue a ser hijo de la luz,
y tenga la luz de la vida y no entre en condenación. Porque la verdadera
creencia se erige en la luz que condena todo mal y al Diablo,
quien es el príncipe de las tinieblas y busca sacar de la luz para llevar a la
condenación. Los que caminan en esta luz llegan al monte de la casa de Dios,
que está establecido sobre todos los montes, y a la enseñanza de Dios,
quien les enseñará Sus caminos.
Estas cosas me fueron reveladas en la luz.

También vi las montañas quemándose, junto con sus escombros; vi las sendas,
los lugares ásperos y torcidos,
allanados y enderezados para que el Señor pudiera entrar en Su tabernáculo.
Estas cosas se encuentran en el corazón del hombre.
Sin embargo, hablar de estas cosas que son internas,
les parecen extrañas a los de corazón áspero, torcido y montañoso.
No obstante, el Señor dice: "`¡Oh, tierra, oye palabra de Jehová!`"^
footnote:[Jeremías 22:29]
La ley del Espíritu es contraria a la mente, espíritu y voluntad carnales,
todo lo cual vive en desobediencia y no se mantiene dentro de la ley del Espíritu.
Vi que esta ley era el amor puro de Dios, la cual estaba sobre mí,
y que yo debía pasar a través de ella,
aunque me sintiera angustiado mientras estaba bajo ella;
porque yo no podía '`morir a la ley, sino por la ley`'^
footnote:[Gálatas 2:19]
que juzgó y condenó todo lo que debe ser condenado.

Vi que muchos que hablaban de la ley, nunca habían experimentado la ley como su tutor;
y que muchos que hablaban del evangelio de Cristo,
nunca habían experimentado la vida e inmortalidad sacadas a la luz por este.
Ustedes que han estado bajo ese tutor y la condenación de este, conocen estas cosas,
porque aunque el Señor me reveló estas cosas en secreto ese día,
han sido predicadas por Su Espíritu eterno desde los tejados de las casas.
En la medida que ustedes sean introducidos en la ley,
y a través de la ley lleguen a morir a ella,
y experimenten la justicia de la ley cumplida en ustedes,
así experimentarán después lo que es ser introducidos en la fe,
y a través de la fe ser sacados de debajo de la ley; y así,
al permanecer en la fe (de la que Cristo es el autor) tendrán
paz para con Dios y entrada a Él. Pero si apartan su mirada
de la fe y se desvían de eso que los mantendría en la victoria,
y se ocupan de cosas y palabras carnales,
serán llevados de nuevo a la esclavitud de la carne, y a la ley,
la cual tiene dominio sobre la carne y el pecado, y obra ira,
y volverán a aparecer las obras de la carne.
Pero la ley de la fe,
o la ley del Espíritu de vida (la cual es el amor de Dios que viene por medio de Jesús,
quien es el fin de la ley para justicia), libera de la ley del pecado y muerte.
Ningún hombre de mente carnal conoce esta ley de vida, sin embargo,
los tentarán a ustedes para alejarlos del Espíritu y acercarlos a la carne,
y así a la esclavitud.

Por tanto, ustedes, los que conocen el amor de Dios,
la ley de Su Espíritu y la libertad que es en Jesucristo, permanezcan firmes en Él,
en esa divina fe de la que Él es el autor en ustedes,
y no se sujeten de nuevo al yugo de esclavitud.
Porque el ministerio y la enseñanza de Cristo Jesús llevan a la libertad,
pero el ministerio que es del hombre,
por medio del hombre y permanece en la voluntad del hombre,
lleva a la esclavitud y coloca debajo de la sombra de muerte y tinieblas.

Por consiguiente,
nadie puede ser ministro de Cristo Jesús a menos que esté en el Espíritu eterno,
el cual era antes de que las Escrituras fueran dadas,
porque si el tal no tiene Su Espíritu,
no es de Él. Aunque los que Lo odian todavía tienen suficiente de Su luz para condenarlos,
no pueden llevar a nadie a la unidad y comunión en
el Espíritu a menos que ellos estén en Él;
porque la Semilla de Dios es una piedra pesada para la voluntad egoísta,
carnal y terrenal,
que reina en sus propios conocimientos y entendimientos (que deben perecer),
y en una sabiduría que es diabólica.
Además, el Espíritu de Dios es entristecido,
afligido y apagado por eso que lleva a la esclavitud carnal,
y eso que pelea contra el Espíritu de Dios debe morir por medio de Él,
"`porque el deseo de la carne es contra el Espíritu,
y el del Espíritu es contra la carne; y estos se oponen entre sí.`"^
footnote:[Gálatas 5:17]
La carne desea tener su libertad y el Espíritu desea tener Su libertad,
pero el Espíritu debe tener Su libertad y no la carne.
Por tanto, si apagan al Espíritu, se unen a la carne y se convierten en siervos de ella,
son juzgados y atormentados por el Espíritu de Dios;
pero si se unen al Espíritu y sirven a Dios en Él,
tienen libertad y victoria sobre la carne y sus obras.

Por ese motivo, manténganse diariamente en la cruz, que es el poder de Dios,
por medio de la cual pueden ver crucificado todo
lo que es contrario a la voluntad de Dios,
y que no entrará en Su reino.
Estas cosas son mencionadas y reveladas aquí para información,
exhortación y consuelo para otros,
tal como el Señor me las reveló en ese día. Ese día me maravillé
de que los hijos de Israel murmuraran por agua y comida,
porque yo habría podido ayunar mucho tiempo sin murmurar, ni pensar en comida.
Pero en otros momentos fui juzgado,
por no estar contento de andar algunas veces sin el agua y pan de vida,
para que yo pudiera aprender y experimentar como sufrir necesidad,
y como tener abundancia.

Pasando de ahí, fui entre los profesantes en Duckenfield y Manchester,
donde me quedé un tiempo y declaré la verdad entre ellos.
Algunos fueron convencidos y recibieron la enseñanza del Señor,
por medio de la cual fueron confirmados y se mantuvieron en la verdad.
Pero otros profesantes estaban furiosos y defendían el pecado y la imperfección,^
footnote:[Él quiere decir que todos ellos insistían en la necesidad
de que el hombre continuara bajo el dominio del pecado,
a lo largo de toda su vida.]
y no podían oír hablar de perfección, ni de una vida santa y sin pecado.
Pero el poder del Señor estaba sobre todos,
aunque ellos estuvieran encadenados bajo tinieblas y pecado (a favor del que luchaban),
y apagaran lo tierno en ellos.

Por esta época hubo una gran reunión de los Bautista en Broughton, Leiscertershire,
con algunos que se habían separado de ellos.
Muchas personas de otras persuasiones asistieron, y yo también fui.
No llegaron muchos de los Bautistas,
pero muchos otros estaban ahí. El Señor abrió mi
boca y la verdad eterna fue declarada entre ellos,
y el poder del Señor estaba sobre todos ellos;
pues en ese tiempo el poder del Señor empezó a brotar
y tuve grandes revelaciones de las Escrituras.
Varios fueron convencidos en aquellas partes, y fueron vueltos de las tinieblas a la luz,
y del poder de Satanás a Dios; y muchos fueron levantados para alabar a Dios.
Cuando razonaba con profesantes y otras personas, algunos se convencían.

Yo todavía, en ocasiones, estaba bajo grandes tentaciones,
y mis sufrimientos internos eran pesados,
pero no podía encontrar a alguien a quien abrirle mi condición, sino sólo al Señor,
a quien clamaba noche y día. Regresé a Nottinghamshire,
y ahí el Señor me mostró que la naturaleza de las cosas que era dañina fuera,
se hallaba dentro, en los corazones y mentes de los hombres perversos.
Vi que la naturaleza de los perros, cerdos y víboras, de Sodoma y Egipto, de Faraón,
Caín, Ismael, Esaú, etc., está en el interior,
aunque la gente había estado mirando hacia afuera.
Y yo clamé al Señor diciendo: "`¿Por qué debo sentirme así,
dado que nunca he sido adicto a cometer esos males?`"
Y el Señor respondió,
que era necesario que yo experimentara algo de todas las condiciones, porque,
de qué otra manera podría hablarles a todas las condiciones.
Y vi en esto el infinito amor de Dios.
También vi que había un océano de tinieblas y muerte, pero asimismo,
que había un océano infinito de luz y amor que fluía sobre el océano de tinieblas.
Y en esto también vi el infinito amor de Dios, y tuve grandes revelaciones.

Mientras caminaba por un costado de la '`casa del campanario`' en Mansfield,
el Señor me dijo: "`Tu comida debe ser lo que la gente pisotea.`"
Y mientras el Señor decía esto,
me mostró que la gente y los profesantes pisoteaban la vida, o sea, la vida de Cristo;
que ellos se alimentaban de palabras y se alimentaban unos a otros con palabras,
pero pisoteaban la vida, pisoteaban la sangre del Hijo de Dios, la cual era mi vida;
y que cuando hablaban de Él, vivían en sus propias ideas vanidosas.
Al principio me pareció extraño,
que yo debía alimentarme de lo que los profesantes altivos del Cristianismo pisoteaban,
pero el Señor me lo reveló claramente por medio de Su Espíritu y Poder eterno.

Entonces la gente llegaba de lejos y de cerca a verme, pero yo temía que me desviaran;
sin embargo, me sentí movido a hablarles y a explicarles varias cosas.
Había un hombre llamado Brown,
que sobre su lecho de muerte tuvo grandes profecías y visiones sobre mí. Habló
de las cosas para las que el Señor me haría un instrumento para Su obra,
y con respecto a otros que entonces eran sólo apariencia,
habló de cómo ellos llegarían a nada; lo cual se cumplió con el tiempo.
Cuando este hombre fue enterrado, una gran obra del Señor cayó sobre mí,
para admiración de muchos, quienes pensaban que había estado muerto;
y por alrededor de catorce días muchos llegaron a verme.
Yo estaba muy alterado en semblante y persona,
como si mi cuerpo hubiera sido moldeado de nuevo, o cambiado.
Mientras estaba en esta condición, el Señor me dio una consciencia y un discernimiento,
a través de lo cual vi claramente, que cuando muchas personas hablaban de Dios,
de Cristo, etc., era la serpiente la que hablaba en ellos;
pero ver esto me resultó muy difícil.
Sin embargo, la obra del Señor continuó en algunos,
y mis tristezas y dificultades comenzaron a desaparecer,
y lágrimas de gozo cayeron de mis ojos,
de modo que habría podido llorar noche y día delante del Señor,
en humildad y quebrantamiento de corazón.

Vi en lo que no tenía fin, cosas que no pueden ser pronunciadas,
y la grandeza e infinitud del amor de Dios que no se puede expresar con palabras.
Pues por el glorioso poder eterno de Cristo,
había sido llevado a través del océano de tinieblas y muerte,
y a través y sobre el poder de Satanás. Incluso,
fui llevado a través de esa oscuridad que cubría todo el mundo,
que lo encadenaba todo y que lo encerraba todo en la muerte.
El mismo poder eterno de Dios que me llevó a través de esas cosas,
fue el que después sacudió la nación, a los sacerdotes, a los profesantes y a la gente.
Entonces yo podía decir, que había estado en la Babilonia, Sodoma,
Egipto y tumba espiritual, pero que, por el poder eterno de Dios, había salido de ahí,
había sido llevado sobre eso,
y había sido trasladado del poder de eso al poder de Cristo.
Vi que la cosecha estaba blanca y que la semilla de Dios yacía espesa en la tierra,
como si fuera trigo sembrado externamente, y me lamenté hasta las lágrimas,
porque no había nadie para recogerla.

Se difundió un informe con respecto a mí,
de que yo era un joven que tenía un espíritu de discernimiento,
por lo que muchos profesantes, sacerdotes y personas, de lejos y de cerca,
llegaban a verme.
El poder del Señor irrumpía y yo tenía grandes revelaciones y profecías,
y les hablaba a ellos de las cosas de Dios,
las cuales escuchaban con atención y en silencio, y se iban y difundían la fama de ellas.
Entonces llegó el tentador y me atacó de nuevo,
acusándome de haber pecado contra el Espíritu Santo,
pero yo no podía ver en qué. Entonces recordé la condición de Pablo, la de cómo,
después de haber sido tomado al tercer cielo y haber visto cosas que no era lícito pronunciar,
le fue enviado un mensajero de Satanás para que lo abofeteara.
De este modo, por el poder de Cristo, también superé esa tentación.

En el año 1648,
mientras estaba sentado en la casa de un amigo en Nottinghamshire (pues para entonces,
el poder de Dios había abierto los corazones de algunos
para que recibieran la palabra de vida y reconciliación),
vi que se abría una gran grieta a lo largo de la tierra,
que junto con la grieta se levantaba un gran humo,
y que tras la grieta se producía un gran temblor.
Vi que esto era la tierra en los corazones de las personas,
los cuales debían ser sacudidos antes de que la semilla de Dios se levantara de la tierra.
Y así fue, porque el poder del Señor empezó a sacudirlos,
y nosotros empezamos a tener grandes reuniones,
y había un gran poder y obra de Dios entre las personas,
para asombro de la gente y de los sacerdotes.

Por ese entonces hubo una reunión de sacerdotes y profesantes en la casa de un juez,
y yo fui.
Ahí estaban discutiendo sobre lo que había dicho Pablo,
que él no había conocido el pecado sino por la ley, la cual dice:
"`No codiciarás;`" ellos creían que esto se refería a la ley externa.
Pero yo les dije que Pablo había dicho esas palabras después de que había sido convencido;
porque él había tenido la ley externa desde antes y había sido criado en ella, incluso,
cuando todavía vivía en la pasión de la persecución.
Que él ahí hablaba de la ley de Dios en su mente,
a la que él servía, y contra la que la ley en sus miembros hacía guerra;
porque lo que él había pensado que era vida para él, había resultado ser muerte.
Entonces, los más sobrios de los sacerdotes y profesantes cedieron,
y estuvieron de acuerdo con que esa no era la ley externa, sino la interna,
la que mostraba la codicia interna de la que habló Pablo después de haber sido convencido.
Pues la ley externa tiene dominio sobre la acción externa,
pero la ley interna tiene dominio sobre la codicia interna.

Después de esto fui de nuevo a Mansfield,
donde hubo una gran reunión de profesantes y gente.
Allí fui movido a orar,
y el poder del Señor fue tan grande que parecía que la casa se sacudía. Cuando terminé,
algunos de los profesantes dijeron que había sido como en los días de los apóstoles,
cuando la casa donde estaban había temblado.
Después de que oré, uno de los profesantes oró, lo que puso muerte y un velo sobre ellos,
y otros de los profesantes fueron afligidos por él y le dijeron que había
un juicio sobre él. Luego él se me acercó y quería que yo orara de nuevo;
pero yo no podía orar en la voluntad del hombre.

Poco después hubo otra gran reunión de profesantes,
y a ella asistió un capitán cuyo nombre era Amor Stoddard.
Ellos estaban hablando sobre la sangre de Cristo, y mientras hablaban de eso,
vi la sangre de Cristo a través de una revelación directa del Espíritu invisible.
Entonces exclamé entre ellos y les dije: "`¿Acaso no ven la sangre de Cristo?
¡Véanla en sus corazones, para que rocíe sus corazones y consciencias de obras muertas,
a fin de que le sirvan al Dios vivo!`"
Pues vi la sangre del Nuevo Pacto,
y cómo debe entrar en el corazón. Esto sobresaltó a los profesantes,
que deseaban tener la sangre sólo fuera de ellos y no dentro.
Pero el capitán Stoddard fue alcanzado,
y cuando vio cómo se esforzaban por derrotarme con muchas palabras dijo:
"`Dejemos hablar al joven; escuchemos al joven hablar.`"

También había un grupo de sacerdotes que eran considerados tiernos;
el nombre de uno era Kellett, y varias personas de corazón tierno fueron a oírlos.
Yo fui movido a ir ante ellos y pedirles,
que le prestaran atención a la enseñanza del Señor en el interior de ellos.
Por ese entonces, el sacerdote Kellett estaba en contra de las casas parroquiales,
pero después consiguió una grande y se convirtió en un perseguidor.

Después de que realicé algunos servicios en esas partes,
crucé Derbyshire hacia mi propio condado (Leicestershire) de nuevo,
y varias personas de corazón tierno fueron convencidas.
Al pasar por ahí, me encontré un gran grupo de profesantes en Warwickshire,
que estaban orando y explicando las Escrituras en un campo.
Ellos me dieron una Biblia y yo la abrí en el capítulo cinco de Mateo,
donde Cristo exponía la ley, y yo les expliqué el estado interno y el estado externo,
sobre lo cual cayeron en una fiera disputa y luego se separaron.
No obstante, el poder del Señor se afianzó.

Luego oí que se iba a realizar una gran reunión para debatir en Leicester,
en la que se decía que iban a estar involucrados Presbiterianos, Independientes,
Bautistas y hombres de la Oración-Común. Se fijó la reunión en la '`casa
del campanario,`' y fui movido por el Señor a asistir y estar entre ellos.
Escuché la discusión y los argumentos de ellos,
algunos estaban en las bancas y el sacerdote estaba en el púlpito,
con una gran cantidad de gente reunida.
Por fin una mujer preguntó: "`¿Qué nacimiento está describiendo Pedro,
cuando habla de renacer de una simiente incorruptible,
por la Palabra de Dios que vive y permanece para siempre?`"
Y el sacerdote le dijo:
"`No permito que una mujer hable en la iglesia;`" aunque
antes había dado libertad de que cualquiera hablara.
Entonces fui envuelto en el poder del Señor,
como en un "`vivo celo,`" y di un paso al frente y pregunté al sacerdote:
"`¿Llamas a este edificio '`iglesia,`' o llamas '`iglesia`' a esta mezcla de personas?`"
Porque la mujer había hecho una pregunta y él debió haberla respondido,
puesto que había dado libertad de que cualquiera hablara.
Pero en lugar de responderme, me preguntó qué era la iglesia.
Yo le dije:
"`La iglesia es '`la columna y baluarte de la verdad,`' hecha de piedras vivas,
miembros vivos; la casa espiritual de la que Cristo es la cabeza.
Pero Él no es cabeza de una mezcla de personas, o de una casa vieja hecha de cal,
piedras y madera.`"
Esto los encendió en ira,
y el sacerdote bajó de su púlpito y otros salieron de sus bancas, y el debate se arruinó.

Pero yo me fui a una gran posada y ahí discutí el
asunto con sacerdotes y profesantes de todo tipo,
y todos ellos estaban enfurecidos.
Sin embargo, yo sostuve la verdadera iglesia y la verdadera Cabeza de la iglesia,
sobre la cabeza de todos ellos, hasta que todos se rindieron y se fueron.
Un hombre parecía afectuoso y por un rato pareció que se unía a mí,
pero de pronto se volvió contra mí,
y se unió a un sacerdote para abogar por el bautismo
infantil (aunque él mismo había sido Bautista antes),
y me dejó solo.
Sin embargo, varios fueron convencidos ese día, entre ellos,
la mujer que había hecho la pregunta junto con su familia;
y el poder y la gloria del Señor brillaron sobre todos.

Después regresé a Nottinghamshire y llegué al Valle de Belvoir.
Mientras recorría el valle, les prediqué el arrepentimiento a las personas,
y muchas fueron convencidas en muchos de sus pueblos;
porque me quedé algunas semanas entre ellos.
Una mañana, mientras estaba sentado junto al fuego,
una gran nube vino sobre mí y me asaltó una tentación; pero me quedé quieto.
Entonces me fue dicho:
"`Todas las cosas se producen por naturaleza,`"
y luego los elementos y las estrellas se apoderaron de mí,
de modo que mi mente se nubló. Pero al estar sentado quieto y en silencio,
las personas de la casa no percibieron nada.
Mientras permanecía quieto bajo la nube y la dejé en paz,
pronto se alzó en mí una esperanza viva y una voz verdadera dijo:
"`Hay un Dios vivo que hizo todas las cosas.`"
Inmediatamente la nube y la tentación se desvanecieron,
y la vida se levantó por encima de todo.
Mi corazón estaba contento y alabé al Dios vivo.
Después de un tiempo,
me encontré con algunas personas que tenían la idea de que no había Dios,
sino que todas las cosas se producían por naturaleza.
Tuve una gran discusión con ellos y los volqué,
e hice que algunos confesaran que hay un Dios vivo.
Luego vi que había sido bueno haber pasado por aquel ejercicio.

Tuvimos grandes reuniones en esos lugares,
pues el poder de Dios irrumpió en esa parte del condado.
Al regresar a Nottinghamshire, encontré un grupo de Bautistas destrozados, y de otros,
y el poder del Señor obró poderosamente y reunió a muchos de ellos.
Después me fui a Mansfield y a sus alrededores,
donde el poder del Señor se manifestó maravillosamente,
tanto en Mansfield como en otros pueblos vecinos.
En Derbyshire, el gran poder de Dios obró de manera maravillosa.
En Eton, un pueblo cerca de Derby, tuvimos una reunión de Amigos,
en la que hubo una manifestación tan poderosa del
poder de Dios que ellos fueron grandemente sacudidos,
y muchas bocas fueron abiertas en el poder del Señor Dios.
Muchos fueron movidos por el Señor a ir a las '`casas del campanario,`'
a los sacerdotes y al pueblo para declararles la verdad eterna.

En cierto momento, mientras estaba en Mansfield,
hubo una reunión de jueces para hablar acerca de la contratación de siervos,
y el Señor puso sobre mí ir y hablarles a los jueces,
que no oprimieran a los siervos en sus salarios.
Así que caminé hacia la posada donde estaban,
pero al encontrarme ahí un grupo de violinistas, no entré,
sino que decidí regresar en la mañana,
cuando pudiera tener una oportunidad más seria de conversar con ellos,
pues pensé que ese no era un momento apropiado.
Pero cuando regresé a la mañana siguiente, ya se habían dio,
y quedé tan afectado que no podía ver.
Le pregunté al posadero dónde se iban a reunir los jueces ese día,
y me dijo que estaban en un pueblo a unas ocho millas de distancia.
Mi vista empezó a regresar, así que salí y recorrí el camino tan rápido como pude.
Cuando llegué a la casa donde estaban, había muchos siervos con ellos,
y exhorté a los jueces a no oprimir a los siervos en sus salarios,
sino a hacer lo correcto y justo con ellos.
Y exhorté a los siervos a cumplir con sus deberes, y a servir honestamente, etc.
Todos recibieron la exhortación amablemente, pues había sido movido por el Señor en esto.

Además, fui movido a ir a varias cortes y '`casas del campanario`' en Mansfield,
y otros lugares, para advertirles que dejaran la opresión y los juramentos,
que se volvieran del engaño al Señor, y que hicieran justicia.
Después de haber estado en la corte en Mansfield,
fui movido a ir y hablarle a uno de los hombres más perversos del condado,
uno que comúnmente estaba borracho, que era un conocido proxeneta,
y que además era poeta.
Yo lo reprendí en el temor del poderoso Dios, por sus malos caminos.
Cuando terminé de hablar con él y lo dejé, fue detrás de mí y me dijo,
que cuando le había hablado, había sido tan impactado,
que apenas le habían quedado fuerzas.
Así fue convencido este hombre y se volvió de su maldad,
y se mantuvo honesto y sobrio para el asombro de la gente que lo había conocido antes.
De esta manera siguió adelante la obra del Señor, y en el lapso de los años 1646,
1647 y 1648, muchos fueron vueltos de las tinieblas a la luz interior.
En ese entonces se realizaban varias reuniones de Amigos, en distintos lugares,
para experimentar la enseñanza de Dios por medio de Su luz, Espíritu y poder;
pues el poder del Señor se manifestaba maravillosamente cada vez más.

Entonces fui arrebatado en el Espíritu, a través de la espada encendida,
al paraíso de Dios.
Todas las cosas eran nuevas,
y toda la creación me despedía un olor diferente al de antes,
más allá de lo que las palabras pueden pronunciar.
Yo no experimentaba nada más que pureza, inocencia y justicia,
siendo renovado a la imagen de Dios por Jesucristo,
al estado en el que había estado Adán antes de caer.
Me fue revelada la creación, y me fue mostrado que todas las cosas tenían sus nombres,
de acuerdo a su naturaleza y virtud.
No sabía qué hacer, si debía practicar la medicina para el bien de la humanidad,
dado que la naturaleza y virtud de las cosas me habían sido reveladas
por el Señor. Pero fui tomado inmediatamente en el Espíritu,
para que viera otro estado, o uno más firme que el estado de inocencia de Adán, es decir,
el estado en Cristo Jesús que nunca caería. Y el
Señor me mostró que los que fueran fieles a Él,
en el poder y luz de Cristo,
llegarían al estado en el que había estado Adán antes de caer,
en el que las admirables obras de la creación y sus virtudes podían ser conocidas
a través de las revelaciones de esa divina Palabra de sabiduría y poder,
por medio de la que habían sido hechas.
El Señor me llevó a grandes cosas, y me fueron reveladas maravillosas profundidades,
más allá de lo que se puede declarar con palabras; sin embargo,
en la medida que las personas se sujeten al Espíritu de
Dios y crezcan en la imagen y poder del Todopoderoso,
recibirán la Palabra de Sabiduría que revela todas las cosas,
y llegarán a conocer la unidad oculta en el Ser Eterno.

Y así viajé al servicio del Señor según Él me guiaba.
Y cuando llegué a Nottingham, el maravilloso poder de Dios estaba ahí entre los Amigos.
De ahí me fui a Clawson, en Leicestershire, en el Valle de Belvoir;
allí también estaba el maravilloso poder de Dios,
en varios pueblos y aldeas donde se reunían los Amigos.
Mientras estaba ahí el Señor me reveló tres cosas relacionadas
con las tres grandes profesiones en el mundo:
medicina, divinidad (así llamada) y ley.
Él me mostró que los médicos se habían salido de la sabiduría de Dios,
por medio de la cual habían sido hechas las criaturas,
y que por eso no conocían sus virtudes.
Me mostró que los sacerdotes se habían salido de la verdadera fe,
de la que Cristo es el autor--la fe que purifica el corazón y da victoria;
la fe mediante la cual las personas tienen acceso
a Dios y por medio de la cual agradan a Dios;
la fe cuyo misterio es guardado en la consciencia limpia.
También me mostró que los abogados se habían salido
de la equidad y de la verdadera justicia,
de la ley de Dios que había sido puesta sobre la
primera transgresión y sobre todo el pecado,
y que estaba en concordancia con el Espíritu de Dios
que era afligido y transgredido en el hombre.
Y que estos tres, los médicos, los sacerdotes y los abogados,
gobernaban el mundo habiéndose salido de la sabiduría, de la fe,
y de la equidad y ley de Dios.
Los primeros, pretendiendo ofrecer la cura del cuerpo; los segundos, la cura del alma;
y los terceros, pretendiendo defender la propiedad de la gente.
Pero vi que ellos estaban fuera de la sabiduría, fuera de la fe,
y fuera de la equidad y perfecta ley de Dios.

Cuando el Señor me reveló estas cosas,
sentí cómo se había extendido Su poder sobre todos,
mediante el cual todos podrían ser reformados,
si lo recibían y se inclinaban ante él. Los sacerdotes podrían
ser reformados y llevados a la verdadera fe;
la fe que es don de Dios.
Los abogados podrían ser reformados y llevados a la ley de Dios;
la ley que concuerda con ese don de Dios que es transgredido en cada uno,
y que lleva al hombre a amar a su prójimo como a sí mismo.
Porque este don es lo que le permite al hombre ver, que si le hace daño a su prójimo,
se hace daño a sí mismo;
y también le enseña a hacer con los demás como quiere que otros
hagan con él. Los médicos podrían ser reformados y llevados a la
sabiduría de Dios (por la que todas las cosas fueron hechas y creadas),
para que pudieran recibir un conocimiento correcto de las cosas creadas,
y entender las virtudes que la Palabra de Sabiduría les había dado.
Me fue revelado mucho con respecto a estas cosas;
cómo todos se habían apartado de la sabiduría de Dios,
y de la justicia y santidad en las que había sido hecho el hombre al principio.
Pero, en la medida que todos crecen en la luz y caminan en la luz (con
la que Cristo ha alumbrado a todo hombre que viene al mundo^
footnote:[Juan 1:9 RVG, RV1602 P]), se convierten en hijos de la luz y del día de Cristo.
En Su día todas las cosas son vistas, visibles e invisibles, por la luz divina de Cristo,
el Hombre espiritual y celestial, por quien todas las cosas habían sido hechas y creadas.

Luego vi con respecto a los sacerdotes,
que aunque ellos permanecían engañados y actuaban por el poder
oscuro (que los mantenía sometidos a ellos y a sus seguidores),
aun así no eran los más grandes engañadores de los que hablan las Escrituras,
porque no habían llegado tan lejos como muchos de ellos.
El Señor me reveló quiénes eran los más grandes engañadores
y cuán lejos podían llegar--es decir,
que los más grandes engañadores eran aquellos
que habían llegado tan lejos como Caín,
como para oír la voz de Dios; aquellos que habían salido de Egipto y cruzado el Mar Rojo,
como para alabar a Dios a la orilla del mar;
aquellos que podían hablar por experiencia de los milagros y maravillas de Dios;
aquellos que habían llegado tan lejos como Coré, Datán y su séquito;
aquellos que habían llegado tan lejos como Balaam, como para hablar la palabra del Señor,
oír Su voz y conocerla, experimentar Su Espíritu, ver la estrella de Jacob,
la hermosura de las tiendas de Israel, el segundo nacimiento,
contra el que ningún encantamiento podía prevalecer.
Que aquellos que podían hablar mucho de sus experiencias de Dios, y que sin embargo,
se volvían del Espíritu y de la Palabra, y negaban la verdad,
eran y siempre serían los grandes engañadores,
mucho más allá de los sacerdotes.

De igual modo entre los cristianos,
que aquellos que habían predicado en el nombre de Cristo, habían hecho milagros,
echado fuera demonios, y que en este tiempo del evangelio,
habían llegado tan lejos como llegaron Caín, Coré y Balaam en el de ellos,
eran y serían los grandes engañadores.
Porque estos podían contar algunas experiencias de Cristo y de Dios, y sin embargo,
no vivían en la vida.
Que estos eran los que guiaban al mundo en pos de ellos,
quienes '`tienen apariencia de piedad, pero niegan su poder,`'^
footnote:[2 Timoteo 3:5 LBLA]
y que internamente pisoteaban al Espíritu.
Que eran los que llevaban a las personas a una forma externa,
pero perseguían a los que estaban en el poder, tal como había hecho Caín;
los que a través de la codicia corrían ávidamente tras el error de Balaam,
al amar la paga de la injusticia.
Que estos seguidores de Caín, Coré y Balaam desde los días de los apóstoles,
habían hecho que el mundo fuera como un mar.
Vi que los que son como estos pueden engañar ahora,
tal como lo hicieron aquellos en épocas anteriores,
pero que es imposible para ellos engañar a los elegidos,^
footnote:[Con el término "`escogidos,`" Fox se refiere
a aquellos que habitan y permanecen en Cristo,
el Elegido de Dios,
y que así "`hacen firme su vocación y elección`" (2 Pedro 1:10). Ni George Fox,
ni ninguno de los primeros Amigos,
eran defensores de la predestinación y condenación individual.]
pues son escogidos en Cristo,
en Aquel que era antes de que el mundo comenzara y antes del engañador;
aunque otros pueden ser engañados en sus revelaciones y profecías,
por no mantener sus mentes en el Señor Jesucristo,
quien Se abre y revela a los que son de Él.

Vi el estado de estos, tanto de sacerdotes como de personas,
quienes al leer las Escrituras alzan mucho la voz contra Caín, Esaú y Judas,
y contra otros hombres perversos de tiempos pasados
que son mencionados en las Sagradas Escrituras,
pero no ven en sí mismos la naturaleza de Caín, de Esaú, de Judas, ni de esos otros.
Que estos decían que "`ellos, ellos, ellos`" eran los malos,
eximiéndose de tener nada que ver con esa naturaleza;
pero cuando algunos de estos hombres llegaron a ver
dentro de sí mismos con la luz y Espíritu de verdad,
entonces dijeron "`yo, yo, yo; yo mismo he sido Ismael, Esaú, etc.`"
Pues llegaron a ver en sí mismos la naturaleza desenfrenada de Ismael,
la naturaleza de Caín, Esaú, Coré y Balaam, la naturaleza del hijo de perdición,
que se levanta contra todo lo que es llamado Dios en ellos.

Vi que el hombre caído se había metido en las Escrituras
y estaba encontrando fallas en los antes mencionados,
y también en los judíos apóstatas, llamándolos robles orgullosos y cedros altivos,
toros gordos de Basán, novillas salvajes, víboras, serpientes, etc.,
acusándolos de ser ellos mismos los que cerraban sus ojos, tapaban sus oídos,
endurecían sus corazones y eran tardos para oír. Que eran ellos los que odiaban la luz,
se rebelaban contra ella, y apagaban, irritaban y contristaban al Espíritu.
Que eran ellos los que caminaban ultrajando al Espíritu de gracia,
volvían la gracia de Dios en libertinaje, resistían al Espíritu Santo,
tenían la forma de piedad, pero se volvían contra el poder.
Que ellos internamente eran los lobos rapaces vestidos de oveja, pozos sin agua,
nubes sin lluvia, árboles sin fruto, etc.
Pero cuando estos, que estaban tan ocupados buscando fallas en otros,
y se creían libres de estas cosas, se miraron a sí mismos,
y con la luz de Cristo se examinaron completamente,
encontraron suficiente de eso en sí mismos.
Entonces el grito ya no fue "`es él, o son ellos,`" como antes, sino "`yo,
y somos nosotros los que nos hallamos en estas condiciones.`"

También vi que las personas leen las Escrituras sin un correcto sentido de ellas,
y sin aplicarlas correctamente a sus propios estados y condiciones.
Porque cuando leen que la muerte había reinado desde Adán hasta Moisés,
que la ley y los profetas habían sido hasta Juan,
que el más pequeño en el reino era mayor que Juan,
leen estas cosas y se las aplican a otros,
pero no se vuelven al interior para encontrar la verdad de estas cosas en ellas mismas.
Pero a medida que estas cosas me eran reveladas,
vi cómo reinaba la muerte sobre ellos desde Adán hasta Moisés, es decir,
desde que entraron en la transgresión hasta que llegaron al ministerio de condenación,
el cual refrena a las personas del pecado que trae muerte.
Luego, cuando se ha atravesado la ministración de Moisés,
el ministerio de los profetas llega a ser leído y entendido,
el cual se extiende a través de figuras,
tipos y sombras hasta Juan--el más grande profeta nacido de una mujer--cuya ministración
prepara el camino del Señor al derribar montañas exaltadas y enderezar calzadas.
Conforme se pasa a través de esta ministración,
se llega a experimentar una entrada al reino eterno.
Vi claramente que nadie podía leer a Moisés correctamente sin el espíritu de Moisés,
por medio del cual Moisés había visto cómo había
sido hecho el hombre a imagen de Dios en el paraíso,
cómo había caído, cómo se había apoderado de él la muerte,
y cómo habían quedado todos los hombres bajo dicha muerte.
Vi cómo había recibido Moisés la ley pura que se extendía sobre todos los transgresores,
y cómo los animales limpios (que eran figuras y tipos) eran ofrecidos,
después de que el pueblo había entrado en la ley justa que
se extendía sobre la primera transgresión. Que tanto Moisés
como los profetas habían visto a través de los tipos y sombras,
y más allá de ellos, y habían visto a Cristo, el gran Profeta que vendría a cumplirlos.

Vi que nadie podía leer las palabras de Juan correctamente,
con el verdadero entendimiento de ellas,
sino en y con el mismo Espíritu divino por el que Juan las había dicho,
y mediante la luz ardiente y brillante del Espíritu enviada por Dios.
Porque por medio de ese Espíritu, sus naturalezas torcidas podrían ser enderezadas,
sus naturalezas ásperas podrían ser suavizadas,
la naturaleza en ellos que extorsiona y hace violencia podría ser echada,
aquellos que habían sido hipócritas podrían llegar a producir frutos dignos de arrepentimiento,
la montaña de pecado y terrenalidad en ellos podría ser abatida,
y el valle en ellos podría ser alzado,
para que en su interior pudiera haber una camino preparado para el Señor; y así,
el menor en el reino sería mayor que Juan.
Pero que todos debían conocer primero la voz que clama en el desierto de sus corazones,
que por la transgresión se habían convertido en un desierto.

Así vi que era fácil decir que la muerte había reinado desde Adán hasta Moisés,
y que la ley y los profetas habían sido hasta Juan,
y que el menor en el reino era mayor que Juan,
pero que nadie podía conocer estas cosas excepto
por el mismo Santo Espíritu en el que Moisés,
los profetas y Juan habían estado.
Vi que nadie podría conocer el significado espiritual de las palabras de Moisés,
de los profetas, o de Juan, ni ver sus caminos y viajes, mucho menos,
ver a través de ellos y hasta el final de ellos en el reino,
a menos que tuviera el Espíritu y la luz de Jesús;
ni podría conocer las palabras de Cristo y Sus apóstoles sin Su Espíritu.
Pero que a medida que el hombre, por medio del Espíritu y poder de Dios,
llegara a Cristo (quien cumple los tipos, figuras, sombras,
promesas y profecías que se referían a Él),
y fuera guiado por el Espíritu Santo a la verdad y sustancia de
las Escrituras (a sentarse en Aquel que es el autor y fin de ellas),
las leería y entendería con provecho y gran deleite.

Además, cuando fui llevado a Su imagen en justicia y santidad, y al paraíso de Dios,
Él me dejo ver cómo había sido hecho Adán un alma viviente; y también,
la estatura de Cristo, el misterio que había estado escondido por edades y generaciones,
cuyas cosas son difíciles de pronunciar y que no pueden ser sobrellevadas por muchos.
Porque, entre todas las sectas del llamado Cristianismo con las que he conversado,
no he encontrado ninguna que soporte oír de que el
hombre puede ser llevado a la perfección de Adán,
a esa imagen de Dios, a la justicia y santidad en las que estaba Adán antes de caer,
para ser limpio, puro y sin pecado, tal como lo había sido él. Por tanto,
¿cómo soportarían oír de alguien creciendo a la medida
de la estatura de la plenitud de Cristo,
cuando no pueden soportar oír que alguien, mientras esté en la tierra,
puede llegar al mismo poder y Espíritu en los que estaban los profetas y apóstoles?
Pero, es una verdad indiscutible,
que nadie puede entender correctamente los escritos de ellos
sin el mismo Espíritu por el que fueron escritos.

Entonces el Señor Dios me reveló por Su invisible poder,
que "`todo hombre estaba alumbrado por la divina luz de Cristo en una medida.`"
Vi cómo brillaba a través de todos,
y cómo todos los que creían en dicha luz salían de
la condenación y entraban en la luz de la vida,
y se convertían en hijos de ella;
pero que aquellos que la aborrecían y no creían en ella, eran condenados por ella,
aunque profesaran a Cristo.
Esto lo vi en las revelaciones puras de la luz, sin la ayuda de algún hombre;
ni sabía entonces dónde encontrarlo en las Escrituras,
aunque después al escudriñar las Escrituras, lo encontré.^
footnote:[Ver, por ejemplo, Juan 1:9; Romanos 1:19; Tito 2:11-12; Juan 3:19, 16:8]
Porque vi en esa Luz y Espíritu que existían antes de que las Escrituras fueran dadas,
y guiaran a los hombres santos de Dios a darlas,
que todos debían llegar a ese Espíritu si deseaban conocer correctamente a Dios,
o a Cristo, o las Escrituras; es decir,
el Espíritu que había sido el líder y maestro de los que escribieron las Escrituras.

Pero observé un embotamiento y pesada somnolencia sobre la gente,
lo cual me asombró. Porque a veces, cuando me disponía a dormir,
mi mente era llevada sobre todo hasta el principio,
en eso que es desde la eternidad hasta la eternidad,
y veía que la muerte tenía que pasar sobre ese estado somnoliento y pesado;
y yo le decía a la gente que debían llegar a experimentar
la muerte de esa naturaleza somnolienta y pesada,
y una cruz contra ella en el poder de Dios,
para que sus mentes y corazones pudieran estar en las cosas de arriba.

En una ocasión en particular, mientras caminaba en los campos, el Señor me dijo:
"`Tu nombre está escrito en el libro de la vida del Cordero,
que era antes de la fundación del mundo.`"
Y mientras el Señor hablaba, yo creí y lo vi en el nuevo nacimiento.
Luego, un tiempo después, el Señor me ordenó salir al mundo,
el cual vi que era como un desierto lleno de zarzas y espinos;
y cuando lo hice en el gran poder del Señor con la Palabra de vida,
el mundo se hinchó e hizo un ruido como de grandes y furiosas olas del mar.
Sacerdotes y profesantes, magistrados y personas,
todos eran como un mar cuando llegué a proclamar el día del Señor entre ellos,
y a predicarles el arrepentimiento.

Fui enviado a volver a la gente de las tinieblas a la luz,
para que pudieran recibir a Jesucristo; porque a todos los que Lo recibieran en Su luz,
vi que Él les daría poder de ser hechos hijos de Dios,
lo que yo había obtenido al recibir a Cristo.
Yo debía dirigir a las personas al Espíritu que dio las Escrituras,
por medio del cual podrían ser conducidas a toda verdad, y así hasta Cristo y Dios,
tal como lo habían sido las que dieron las Escrituras.
Debía volverlas a la gracia de Dios y a la verdad en el corazón, que vinieron por Jesús,
para que fueran enseñadas por medio de esa gracia, la cual les trae salvación,
para que sus corazones fueran establecidos en ella y sus palabras sazonadas,
y todas pudieran llegar a conocer que su salvación está cerca.

Vi que Cristo había muerto por todos los hombres
y que había sido la propiciación para todos;
que Él iluminaba a todos los hombres y mujeres con Su divina y salvadora luz,
y que nadie podría ser un verdadero creyente sino aquel que creyera en ella.
Vi que '`la gracia de Dios que trae salvación,
había sido manifestada a todos los hombres,`'^
footnote:[Tito 2:11]
y que '`la manifestación del Espíritu de Dios había sido dada a cada uno,
para provecho.`'^
footnote:[1 Corintios 12:7]
Vi estas cosas sin ayuda del hombre y sin la letra de las Escrituras,
aunque están escritas en la letra;
pero yo las vi en la luz del Señor Jesucristo y mediante Su inmediato Espíritu y poder,
tal como las habían visto los santos hombres de Dios
por quienes fueron escritas las Sagradas Escrituras.
Pero yo no tenía poca estima por las Sagradas Escrituras.
En realidad, eran muy preciosas para mí,
porque yo estaba en ese Espíritu mediante el cual habían sido dadas,
y las cosas que el Señor me reveló, después las encontré en concordancia con Ellas.
Podría hablar mucho de estas cosas y muchos volúmenes se podrían escribir,
pero todos resultarían demasiado cortos para expresar el infinito amor,
sabiduría y poder de Dios al prepararme, hacerme apto y equiparme para el servicio.
Él me escogió, por un lado, para que viera las profundidades de Satanás, y por otro,
para revelarme los misterios divinos de Su propio reino eterno.

Entonces,
cuando el Señor Dios y Su Hijo Jesucristo me enviaron
al mundo a predicar Su evangelio eterno y Su reino,
me alegré de que se me ordenara volver a las personas a esa luz,
Espíritu y gracia en el interior,
por medio de lo cual todas podrían conocer su salvación y su camino a Dios--es decir,
conocer a ese Espíritu Divino que las conduciría a toda verdad,
y que yo infaliblemente sabía que no engañaría a nadie.
Yo debía, con y por este poder divino y Espíritu de Dios, y, con y por la luz de Jesús,
sacar a las personas de sus propios caminos y llevarlas a Cristo, el camino nuevo y vivo;
de las iglesias que los hombres había hecho y congregado, a la iglesia en Dios,
la congregación inscrita en el cielo, de la que Cristo es la cabeza.
Debía sacarlas de los maestros del mundo establecidos por el hombre,
para que pudieran aprender de Cristo, quien es el camino, la verdad y la vida,
y de quien el Padre dice: "`¡Este es mi Hijo amado,
a Él oíd!`" Debía sacarlas de la adoración del mundo,
para que pudieran conocer al Espíritu de Verdad en lo íntimo y ser guiadas por Él,
a fin de que en el Espíritu pudieran adorar al Padre de los espíritus,
quien busca que tales adoradores Lo adoren; pues los que no adoran en este Espíritu,
no conocen lo que adoran.

Fui enviado a sacar a las personas de todas las religiones del mundo, que son vanas,
para que pudieran conocer la religión pura, y visitar a los huérfanos,
a las viudas y a los extranjeros, y se pudieran guardar sin mancha del mundo;
porque entonces no habría tantos mendigos, cuya visión a menudo entristecía mi corazón,
ya que evidenciaba la gran dureza de corazón entre los que profesaban el nombre de Cristo.
Debía sacarlas de la comunión,
oración y canto del mundo que se mantenían en formas sin poder,
para que la comunión de ellas pudiera ser en el Espíritu
Santo y en el Eterno Espíritu de Dios;
y para que pudieran orar en el Espíritu Santo,
y cantar en el Espíritu y con la gracia que viene por Jesús,
haciendo melodías en sus corazones al Señor,
que ha enviado a Su amado Hijo para que sea el Salvador de ellas,
y ha hecho que Su sol celestial brille sobre todo el mundo, y a través de todas ellas,
y que Su lluvia celestial caiga sobre justos e injustos (tal como
Su lluvia externa cae y Su sol externo brilla sobre todos),
todo lo cual es el inefable amor de Dios por el mundo.
Debía sacar a las personas de todas las ceremonias judías y fábulas paganas,
y de las invenciones de los hombres y doctrinas mundanas,
por medio de las cuales ellas eran llevadas de un lado a otro, y de una secta a otra.
Debía sacarlas de los pobres rudimentos,
con sus escuelas y facultades para formar ministros para Cristo,
quienes en realidad son ministros de su propia hechura, pero no de la de Cristo.
Debía sacarlas de sus imágenes y cruces, y bautismo de infantes,
con todos sus llamados '`días santos`' y vanas tradiciones,
que habían sido constituidos después de los días de los apóstoles,
y contra los cuales estaba el poder del Señor. Y en el temor y autoridad de Su poder,
fue movido a declarar contra todo ello,
y contra todos los que no predicaban gratuitamente,
por ser los que claramente no habían recibido gratuitamente de Cristo.

Además, cuando el Señor me envió al mundo,
Él me prohibió quitarme el sombrero ante nadie, superior o inferior,
y me demandó el "`tú`" y el "`ti`" para todos los hombres y mujeres,
sin tener en cuenta a ricos o pobres, grandes o pequeños.^
footnote:[En esta época de la historia,
el uso correcto y llano de "`tú`" y "`ti`" para una persona,
empezaba a darle paso al "`usted`" y "`ustedes.`"
En los años 1600,
se puso de moda (como un medio para mostrar honor o adulación) utilizar el "`usted`"
y "`ustedes`" para dirigirse a personas de mayor estatus social,
mientras que el "`tú`" y "`ti`" se reservaban para los sirvientes,
los niños o las personas de menor posición social o económica.
George Fox y todos los primeros Amigos se ciñeron a lo que entonces se consideraba
"`lenguaje llano`" (utilizar el "`tú`" y "`ti`" para cada persona individual,
y el "`usted`" y "`ustedes`" para dos o más),
en lugar de mostrar preferencia al dirigirse a ciertos individuos en plural.]
Mientras viajaba de un lado a otro,
no debía decirles a las personas "`buenos días`" ni "`buenas noches,`"
ni debía inclinarme ni arrastrar mi pierna ante nadie;^
footnote:[Los saludos normales entre pares en esta época consistían
en arrastrar el pie derecho hacia atrás en el suelo,
hacer una reverencia mientras se quitaba el sombrero, y a continuación,
halagar comúnmente al otro con títulos como "`su señoría,`" "`su eminencia,`" etc.]
esto hizo que las sectas y profesantes se enfurecieran.
Pero el poder del Señor me llevó por encima de todo para Su gloria,
y muchos se volvieron a Dios en poco tiempo;
porque el día celestial del Señor había brotado en lo alto e irrumpido rápidamente,
y mediante su luz muchos llegaron a ver dónde estaban.

Pero, ¡oh, la rabia que apareció entonces en los sacerdotes, magistrados,
profesantes y personas de todo tipo, especialmente en los sacerdotes y profesantes!
Porque,
aunque decirle "`tú`" a una sola persona estaba de
acuerdo con su propia educación y reglas gramaticales,
y en concordancia con la Biblia, aun así no podían soportar escucharlo.
Y en cuanto al '`honor del sombrero,`' debido a que yo no podía quitármelo ante ellos,
todos se enfurecían. Pero el Señor me mostró que este era un honor de abajo que
Él abatiría y pondría en el polvo--un honor que la carne orgullosa buscaba,
pero que no buscaba el honor que venía de Dios.
Que era un honor inventado por los hombres en la caída y alienación de Dios,
y que se ofendían si no lo recibían; sin embargo, querían ser considerados santos,
miembros de la iglesia y grandes Cristianos.
Pero Cristo dijo: "`¿Cómo podéis vosotros creer,
pues recibís gloria los unos de los otros,
y no buscáis la gloria que viene del Dios único?`"^
footnote:[Juan 5:44]
Y, "`Gloria de los hombres no recibo;`"^
footnote:[Juan 5:41]
mostrando que hay un honor que los hombres quieren recibir y dar,
pero que Cristo no quiere nada de este.
Que este es el honor que Cristo no recibiría y el que debía ser puesto en el polvo.

¡Oh, la rabia y el desprecio, el ardor y la furia que se levantaron de esto! ¡Oh,
los golpes, puñetazos,
palizas y encarcelamientos que padecimos por no quitarnos el sombrero ante los hombres!
Porque esto pronto probó la paciencia y sobriedad de todos los hombres y manifestó lo
que había. A algunos les quitaban violentamente sus sombreros y los tiraban a la basura,
de modo que los perdían totalmente.
El lenguaje grosero y el perverso trato que recibíamos por ese motivo,
son difíciles de expresar,
además del peligro que corríamos de perder nuestras vidas por ese asunto;
todo esto por parte de los grandes profesantes del Cristianismo,
quienes de este modo evidenciaban que no eran verdaderos creyentes.
Y aunque era algo pequeño a los ojos de los hombres,
trajo una tremenda confusión entre todos los profesantes y sacerdotes.
Pero, bendito sea el Señor,
muchos llegaron a ver la vanidad de la costumbre
de quitarse el sombrero delante de los hombres,
y sintieron el peso del testimonio de la Verdad en su contra.

Por este tiempo,
yo me sentía fuertemente impulsado a ir a los tribunales y clamar por justicia,
y hablarles y escribirles a los jueces y magistrados que hicieran justicia.
Les advertía a los que tenían casas para hospedar,
que no debían dejar que la gente tomara más de lo que les haría bien.
Testificaba contras sus fiestas, juegos de mayo, deportes, juegos y espectáculos,
que entrenaban a la gente en la vanidad y ligereza, y los alejaba del temor de Dios.
Y testificaba contra los días que los hombres habían decretado como "`días festivos,`"
porque usualmente eran los días en que más deshonraban a Dios con esas cosas.
En las ferias y mercados, el Señor me hacía declarar contra sus mercancías engañosas,
y contra el engaño y el fraude, y advertirles a todos que negociaran justamente,
hablaran la verdad, que su sí fuera sí, y su no fuera no,
e hicieran con otros como querían que otros hicieran con ellos;
advirtiéndoles del grande y terrible día del Señor que vendría sobre todos ellos.

También me sentía movido a clamar contra todo tipo de música,
y contra los timadores que hacían trucos en sus escenarios,
porque ellos cargaban la vida pura y agitaban las mentes de las personas hacia la vanidad.
También me sentía impulsado a exhortar a los maestros y maestras de escuelas,
para que enseñaran a sus niños sobriedad en el temor del Señor,
y no fueran alimentados y educados en la ligereza, vanidad y descuido.
Asimismo, fui llevado a advertirles a los amos y amas,
padres y madres de familias particulares,
que cuidaran que sus niños y sirvientes fueran educados en el temor del Señor,
y que ellos mismos fueran ejemplos y modelos de sobriedad y virtud para ellos.
Porque vi que así como los judíos tenían que enseñarles
a sus niños y sirvientes la ley de Dios y el antiguo pacto,
y educarlos en él, sí,
y que así como los extranjeros tenían que guardar el sábado entre ellos
y ser circuncidados antes de que pudieran comer de sus sacrificios,
del mismo modo todos los Cristianos y todos los que hacían profesión del Cristianismo,
tenían que educar a sus niños y sirvientes en el nuevo pacto de luz--Cristo
Jesús--quien es la salvación de Dios hasta los confines de la tierra,
para que todos pudieran experimentar su salvación. Por tanto,
tenían que educarlos en la ley de vida, la ley del Espíritu, la ley de amor y de fe,
para que pudieran ser liberados de la ley del pecado y muerte.
Y que todos los Cristianos tenían que ser circuncidados por el Espíritu,
que echa el cuerpo pecaminoso carnal,
para que pudieran llegar a comer del sacrificio celestial--Cristo
Jesús--la verdadera comida espiritual,
de la que nadie puede alimentarse correctamente sino
los que están circuncidados por el Espíritu.
De igual manera, me sentía movido a exhortar a los astrólogos,
quienes arrastraban las mentes de las personas lejos de Cristo,
la resplandeciente estrella de la mañana y Sol de justicia, por quien el sol, la luna,
las estrellas y todas las cosas fueron hechas, quien es la sabiduría de Dios,
y de quien se recibe el conocimiento correcto de todas las cosas.

Pero el espíritu terrenal de los sacerdotes hería mi vida,
y oír el repicar de la campana llamando a la gente a reunirse
en la '`casa del campanario,`' golpeaba mi vida,
porque era como una campana de mercado,
que sonaba para reunir a la gente para que el sacerdote
pudiera exponer su mercancía para la venta.
¡Oh,
las enormes sumas de dinero que eran obtenidas por
el comercio que hacían vendiendo las Escrituras,
y por su predicación,
desde el obispo más alto hasta el sacerdote más bajo! ¿Qué otro comercio en el mundo
es comparable a este?--a pesar de que las Escrituras habían sido dadas gratuitamente,
y que Cristo les había ordenado a Sus ministros que predicaran gratuitamente,
y los profetas y apóstoles habían pronunciado juicio contra
todos los codiciosos mercenarios y adivinos por dinero.
Pero yo fui enviado, en este Espíritu gratuito del Señor Jesús,
a declarar gratuitamente la Palabra de vida y reconciliación,
para que todos pudieran ir a Cristo (quien da gratuitamente
y renueva a la imagen de Dios,
la que el hombre y la mujer tenían antes de la caída),
y pudieran sentarse en los lugares celestiales en Cristo Jesús.

Entonces, mientras iba hacia Nottingham con unos Amigos para asistir a una reunión ahí,
en la mañana del Primer-día, y llegamos a la cima de una colina con vista al pueblo,
divisé la gran '`casa del campanario`' y el Señor me dijo:
"`Debes ir a clamar contra ese gran ídolo y contra los adoradores
en él.`" No les dije nada de esto a los Amigos que estaban conmigo,
sino que continué con ellos a la reunión,
donde el gran poder del Señor se sintió entre nosotros.
Después dejé a los Amigos sentados en la reunión
y me fui a la '`casa del campanario.`' Cuando llegué,
todas las personas me parecieron como campos duros y secos,
y el sacerdote (como un gran terrón de tierra) estaba en su púlpito por encima de todos.
Él tomó como texto las palabras de Pedro:
"`Tenemos también la palabra profética más segura,
a la cual hacéis bien en estar atentos como a una antorcha que alumbra en lugar oscuro,
hasta que el día esclarezca y el lucero de la mañana salga en vuestros corazones.`"^
footnote:[2 Pedro 1:19]
Y le dijo a la gente que esto hablaba de las Escrituras,
por medio de las cuales se debían probar todas las doctrinas, religiones y opiniones.
En ese momento el poder del Señor estaba tan poderosamente
sobre mí y tan fuertemente en mí,
que no me pude reprimir sino que grité y dije: "`¡Oh, no, no son las Escrituras!`"
Y les dije lo que era, a saber,
el Espíritu Santo por medio del cual los santos hombres de Dios habían dado las Escrituras,
y por el que debían ser probadas las opiniones, religiones y juicios;
porque el Espíritu conducía a toda verdad, y así daba el conocimiento de toda la verdad.
Que los judíos habían tenido las Escrituras,
y aun así habían resistido al Espíritu Santo y rechazado a Cristo,
la estrella resplandeciente de la mañana.
Que ellos habían perseguido a Cristo y a Sus apóstoles,
y que habían intentado probar sus doctrinas con las Escrituras,
pero que se habían equivocado de juicio y no las habían probado correctamente,
porque lo habían hecho sin el Espíritu Santo.
Mientras hablaba todas esas cosas entre ellos, llegaron los oficiales y me llevaron,
y me pusieron en una asquerosa y maloliente prisión,
cuyo olor se me metió por la nariz y por la garganta, y fue muy molesto para mí.

Pero ese día el poder del Señor sonó tanto en sus oídos,
que se asombraron de la voz y no pudieron sacarla de sus oídos por un tiempo,
pues habían sido alcanzados por el poder del Señor en la '`casa
del campanario.`' En la noche me llevaron delante del alcalde,
los concejales y alguaciles del pueblo, y cuando fui llevado ante de ellos,
el alcalde estaba malhumorado e irritado,
pero el poder del Señor lo sometió. Me interrogaron detenidamente y les dije cómo me
había movido el Señor a llegar allí. Después de una conversación entre ellos y yo,
me enviaron de regreso a prisión, pero poco tiempo después, el alguacil en jefe,
cuyo nombre era John Reckless, me envió a llamar a su casa.
Cuando llegué su esposa me recibió en el pasillo y dijo:
"`La salvación ha llegado a nuestra casa.`"
Me tomó de la mano y fue muy afectada por el poder del Señor Dios; y su esposo,
niños y sirvientes fueron cambiados, pues el poder del Señor operó sobre ellos.

Me alojé en la casa del alguacil,
y tuvimos grandes reuniones allí. Algunas personas
de considerable posición en el mundo asistieron,
y el poder del Señor apareció notablemente entre ellas.
Este alguacil envió a llamar a otro alguacil,
y a una mujer con la que ellos habían tenido algunos tratos comerciales,
y le dijo a ella frente al otro alguacil,
que ellos habían actuado deshonestamente en los tratos
con ella (porque el otro alguacil y él eran socios),
y que debían hacerle restitución. Esto lo dijo alegremente,
pero el otro alguacil lo negó, y la mujer dijo que ella no sabía nada de eso.
Pero el alguacil dijo amigablemente que había sido así,
y que el otro lo sabía bastante bien;
y tras revelar el asunto y admitir el daño hecho por ellos,
le hizo restitución a la mujer y exhortó al otro alguacil a hacer lo mismo.
El poder del Señor estaba con este amable alguacil y obró un poderoso cambio en él,
y tuvo grandes revelaciones.
El siguiente día de mercado, mientras caminaba conmigo en su recámara en pantuflas, dijo:
"`Tengo que ir al mercado y predicarles a las personas el arrepentimiento;`"
consecuentemente fue al mercado y a varias calles,
y le predicó el arrepentimiento a la gente.

Varios otros en el pueblo también fueron movidos a hablarles al alcalde,
a los magistrados y al pueblo, exhortándolos al arrepentimiento.
En seguida los magistrados se enfurecieron y me enviaron a llamar de la casa del alguacil,
y me mandaron a la prisión común. Cuando comenzaron las sesiones de la corte,
un hombre fue movido a llegar y ofrecerse en mi lugar, cuerpo por cuerpo; sí,
incluso a ofrecer su vida.
Pero cuando yo debía ser llevado delante del juez,
el siervo del alguacil tardó en llevarme a la sesión de la corte,
y cuando llegué el juez ya se había ido.
Entendí que el juez estaba un tanto ofendido y había dicho:
"`Yo habría amonestado al joven si hubiera sido llevado delante de mí;`"
(porque yo estaba encarcelado bajo el nombre de "`El Joven`"). Por tanto,
fui llevado a prisión otra vez y puesto en la cárcel común.
El poder del Señor era grande allí entre los Amigos,
pero las personas empezaron a ser muy groseras,
por lo que el gobernador del castillo envió soldados y las dispersó,
y después de eso se tranquilizaron.
Pero tanto los sacerdotes como la gente estaban asombrados
ante el maravilloso poder que había irrumpido,
y varios de los sacerdotes se enternecieron y algunos confesaron el poder del Señor.

Luego de que fui liberado de la cárcel de Nottingham,
donde había sido mantenido prisionero algún tiempo,
viajé como antes en la obra del Señor. Al llegar a Mansfield-Woodhouse
me encontré con una mujer trastornada bajo el cuidado de un médico,
y con su cabello suelto alrededor de sus orejas.
La mujer estaba atada y el médico estaba a punto de sangrarla,
y muchas otras personas estaban alrededor de ella sosteniéndola con violencia;
pero el médico no pudo sacarle sangre.
Yo les pedí que la desataran y la dejaran en paz,
porque ellos no podían tocar el espíritu que la atormentaba.
Entonces la desataron y fui movido a hablarle,
y en el nombre del Señor le pedí que estuviera callada y quieta, y así fue.
El poder del Señor estabilizó su mente y se compuso,
y después recibió la verdad y continuó en ella hasta la muerte.
El nombre del Señor fue honrado; a quien le pertenece la gloria de toda Sus obras.
Muchas cosas grandes y maravillosas fueron realizadas
por el poder celestial en esos días;
porque el Señor mostró Su omnipotente brazo y manifestó
Su poder para asombro de muchas personas.
Muchas fueran liberadas de grandes dolencias por Su virtud sanadora,
y los demonios fueron sometidos por Su nombre; de lo cual,
se podrían dar ejemplos específicos más allá de lo
que esta época incrédula es capaz de recibir o soportar.
¡Bendito sea para siempre el nombre del Señor y eternamente honrado,
y sea exaltado el brazo de Su glorioso poder y magnificado sobre
todo lo que ha realizado gloriosamente! ¡Qué el honor y la alabanza
de todas Sus obras sean atribuidas sólo a Él!

Mientras estaba en Mansfield-Woodhouse,
fui movido a ir a la '`casa del campanario`' y declararles
la verdad al sacerdote y al pueblo.
Pero las personas se abalanzaron sobre mí con gran furia,
me atacaron al punto de casi sofocarme y ahogarme,
y me golpearon e hirieron cruelmente con sus manos, Biblias y bastones.
Luego me sacaron a rastras, y aunque yo difícilmente me podía sostener de pie,
me pusieron en el cepo, donde estuve sentado algunas horas.
Ellos llevaron látigos de perros y caballos, y me amenazaron con azotarme.
Después de un tiempo me llevaron ante el magistrado,
en la casa de un caballero (donde había mucha gente de gran posición en el mundo), quien,
al ver cuán perversamente había sido yo maltratado,
después de muchas amenazas me dejó en libertad.
Pero la gente ruda del pueblo me echó a pedradas
del pueblo por predicarles la palabra de vida.
Yo apenas me podía mover o permanecer de pie, por el duro trato que había recibido,
sin embargo, haciendo un esfuerzo considerable logré llegar a una milla del pueblo,
y luego me topé con algunas personas que me dieron algo para aliviarme,
porque yo estaba herido en el interior; pero el poder del Señor pronto me sanó de nuevo.
Ese día algunas personas fueron convencidas de la
verdad del Señor y se volvieron a Su enseñanza,
para mi regocijo.

Luego me fui a Leicestershire acompañado por varios Amigos.
Por esa zona había algunos Bautistas a quienes quería ver y con quienes quería hablar,
porque se había separado de la adoración nacional.
Un hombre llamado Oates, que era uno de sus principales maestros, y otros de sus líderes,
además de varios otros de su grupo, llegaron a Barrow para conocernos,
y allí conversamos con ellos.
Uno de ellos dijo: "`Todo lo que no proviene de la fe, es pecado.`"
Por lo que yo les pregunté: "`¿Qué es fe y cómo es obrada en el hombre?`"
Pero ellos se desviaron de la pregunta y empezaron a hablar de su bautismo en agua.
Entonces les pregunté si las montañas de pecado en ellos habían sido abatidas y derribadas,
y si los caminos ásperos y torcidos en ellos habían sido allanados y enderezados,
porque consideraban que esas Escrituras hablaban de montañas y caminos externos.
Pero yo les dije que debían encontrar esas cosas en sus propios corazones,
lo que pareció extrañarles.
Les preguntamos quien había bautizado a Juan el Bautista,
y quien había bautizado a Pedro, a Juan y al resto de los apóstoles,
y les pedimos que probaran con las Escrituras que ellos habían sido bautizados en agua;
pero guardaron silencio.
Luego les preguntamos: "`Viendo que Judas,
el que traicionó a Cristo y fue llamado hijo de perdición, se ahorcó,
¿quién es entonces el hijo de perdición del que habla Pablo,
ese que se sienta en el templo de Dios y se levanta contra todo lo que se llama Dios?
¿Cuál es ese templo de Dios en el que este hijo de perdición se sienta?
Los que traicionan a Cristo en sí mismos,
¿acaso no están en la naturaleza con la que Judas traicionó a Cristo externamente?`"
Pero ellos no sabían qué hacer con estas cosas, ni qué decir.
Por tanto, después de algo más de conversación se fueron,
y algunos de ellos nos llegaron a amar.

Pasando de ahí,
oí de unas personas que estaban en prisión en Coventry por
motivos de religión. Y mientras me dirigía a la cárcel,
la palabra del Señor vino sobre mí diciendo: "`Mi amor siempre fue para ti,
y tú estás en Mi amor.`"
Yo me sentí abrumado por la consciencia del amor de Dios,
y fui muy fortalecido en mi hombre anterior.
Pero cuando llegué a la cárcel donde estaban los prisioneros,
un gran poder de las tinieblas me golpeó,
y me senté quieto con mi espíritu unido al amor de Dios.
Eventualmente, los prisioneros comenzaron a vociferar, a jactarse y a blasfemar,
por lo que mi alma se afligió mucho.
Ellos decían que eran Dios, pero nosotros no podíamos soportar oír esas cosas.
Cuando se calmaron,
me puse de pie y les pregunté si ellos hacían esas
cosas movidos por el Espíritu o por las Escrituras;
ellos dijeron que por las Escrituras.
Como yo tenía una Biblia a mano, les pedí que me señalaran las Escrituras que los movían,
y me mostraron el lugar donde se bajaba una sábana delante de Pedro,
y se le decía que lo que Dios había santificado no debía llamarlo común o inmundo.
Cuando yo les demostré que esa Escritura no probaba nada para el propósito de ellos,
sacaron la que habla de que Dios reconcilia todas las cosas con Él,
tanto las cosas del cielo como las de la tierra.
Les dije que reconocía esa Escritura también,
pero les demostré que tampoco probaba nada para el propósito de ellos.
Luego, viendo que ellos decían que eran Dios,
les pregunté si sabían si iba a llover al día siguiente o no.
Ellos dijeron que no podían decirlo; yo les dije: "`Dios sí puede.`"
Luego les pregunté, si ellos pensaban que estarían siempre en esa condición,
o si cambiarían. Ellos respondieron que no podían decirlo, entonces les dije:
"`Dios puede decirlo, y Dios no cambia.
Ustedes dicen que son Dios, y sin embargo, no saben si van a cambiar o no.`"
Así que estaban confundidos, y por un rato, bastante abatidos.
Después de reprenderlos por sus expresiones blasfemas, me fui,
porque me di cuenta de que eran Ranters.^
footnote:[Los ranters eran un grupo un tanto extraño, no-conformista,
que surgió a mediados del siglo XVII,
y que recibió su nombre debido a sus discursos y prácticas extravagantes.
Algunos de ellos parecen haber sido auténticos buscadores de la verdad,
quienes (en palabras de William Penn) "`no se mantuvieron en la humildad y temor de Dios,
y después de la abundancia de revelación, se exaltaron por encima de toda medida;
y por no mantener sus mentes en una humilde dependencia de Aquel que les
había abierto el entendimiento para ver grandes cosas en Su ley,
se desbordaron en sus propias imaginaciones, y mezclándolas con las revelaciones divinas,
dieron lugar a un nacimiento monstruoso, para escándalo de los que temían a Dios.`"
Los ranters a menudo interrumpían las reuniones religiosas establecidas, gritando,
cantando, tocando instrumentos o haciendo otros ruidos fuertes.]
Yo no me había encontrado ninguno de este tipo antes,
y admiré la bondad del Señor al aparecerse a mí, antes de ir entre ellos.
No mucho después de esto, uno de esos Ranters, cuyo nombre era Joseph Salmon,
presentó un documento o libro de retractación, por el que fueron puestos en libertad.

De Coventry me fui a Atherstone, y como llegué el día de conferencia para ellos,
fui movido a ir a su capilla para hablarles a los sacerdotes y al pueblo.
En general, estuvieron bastante tranquilos,
excepto por unos pocos que se enfurecieron y querían que mis parientes me ataran.
Les declaré mucha cosas, de cómo Dios había venido para enseñar a Su pueblo Él mismo,
y apartarlo de todos sus maestros hechos por los hombres, para que oyeran a Su Hijo.
Algunos fueron convencidos ahí.

Luego fui a Market-Bosworth,
donde había una conferencia también. El que predicó ese día fue Nathaniel Stevens,
el sacerdote del pueblo donde yo había nacido.
Él se enfureció mucho cuando le hablé a él y al pueblo, y les dijo que yo estaba loco,
aunque le había dicho antes al coronel Purfoy,
que nunca se había producido una planta así en Inglaterra.
Él le pidió a la gente que no me escuchara, y así,
al ser incitadas por este sacerdote embustero,
se abalanzaron sobre nosotros y nos sacaron a pedradas del pueblo,
aunque no nos hicieron mucho daño. Sin embargo,
algunas personas fueron enternecidas ese día,
otras fueron confirmadas en la verdad al ver la rabia,
tanto de los sacerdotes como de los profesantes,
y otras gritaron que el sacerdote no se atrevía a quedarse para probar su ministerio.

Mientras viajaba por los mercados, ferias y varios lugares,
vi muerte y oscuridad en todas las personas,
donde el poder del Señor Dios no los había sacudido.
Mientras atravesaba Leicestershire, llegué a Twy-Cross,
donde había algunos oficiales de aduanas.
Fui movido por el Señor a acercarme a ellos y advertirles
que tuvieran cuidado de oprimir al pobre;
y la gente se afectó mucho por esto.
Había en dicho pueblo un hombre rico que hacía mucho tiempo estaba enfermo,
y que había sido desahuciado por los médicos.
Algunos Amigos del pueblo me pidieron que fuera a verlo.
Fui adonde él, a su recámara, y le hablé la palabra de vida y fui movido a orar por él,
y el Señor fue implorado y le restauró la salud.
Pero cuando bajé las escaleras a una habitación inferior,
y les hablaba a unos sirvientes y a otras personas que estaban ahí,
un sirviente salió furioso de otra habitación con una espada desenvainada en su mano,
y la colocó en mi costado.
Lo miré fijamente y le dije: "`¡Ay de ti, pobre criatura! ¿Qué harás con tu arma carnal?
No es más que una pajita para mí.`" Los espectadores se preocuparon mucho,
y el sirviente se fue furioso y lleno de ira.
Pero cuando le llegó la noticia de esto a su amo, lo despidió de su servicio.
Así me preservó el poder del Señor y levantó al hombre débil,
quien después de esto fue muy amable con los Amigos.
Y cuando regresé al pueblo, tanto él como su esposa fueron a verme.

Después de esto fui movido a ir a Derbyshire,
donde el gran poder de Dios estaba entre los Amigos.
Y fui a Chesterfield, donde un tal Britland era sacerdote.
Él veía más allá que el común de los sacerdotes,
porque había sido parcialmente convencido,
y había hablado mucho a favor de la Verdad antes de ser
sacerdote ahí. Pero cuando el sacerdote de ese pueblo murió,
él obtuvo la casa parroquial y se atragantó con ella.
Fui movido a hablarle a él y a las personas del gran amor de Dios,
para que se apartaran de todas las enseñanzas de
los hombres y se acercaran a las de Dios,
y él no pudo oponerse a lo que dije.
Pero me llevaron delante del alcalde y me amenazaron con enviarme a mí,
y a algunos otros, a la casa de corrección,
y nos mantuvieron bajo custodia hasta altas horas de la noche.
Luego, los oficiales, junto con los vigilantes, nos sacaron del pueblo,
dejando que nos las arregláramos como pudiéramos.
Así, pues, giré mi curso hacia Derby, teniendo uno o dos amigos conmigo.
En nuestro camino nos topamos con muchos profesantes,
y en Kidsey-Park muchos fueron convencidos.

Luego, al llegar a Derby, me quedé en la casa de un médico,
cuya esposa estaba convencida, junto con varios otros del pueblo.
Mientras caminaba en mi recámara,
sonó la campana de la '`casa del campanario,`' y al escucharla golpeó mi vida.
Por tanto, le pregunté a la mujer de la casa,
la razón por la que estaba sonando la campana.
Ella me dijo que iba a haber una gran conferencia ahí ese día,
y que muchos oficiales del ejército, sacerdotes y predicadores estarían presentes,
y un coronel que era predicador.
Entonces fui movido por el Señor a ir y cuando ellos terminaron,
les hablé lo que el Señor me había mandado, y ellos estuvieron bastante tranquilos.
Pero luego,
llegó un oficial que me cogió de la mano y me dijo
que yo y los otros dos que estaban conmigo,
debíamos ir delante de los magistrados.

Cerca de la primera hora después del mediodía nos llevaron delante de ellos,
y nos preguntaron la razón por la que habíamos llegado ahí. Yo les dije:
"`Dios nos ha movido a hacerlo;`" y agregué,
"`Dios no mora en templos hechos por manos.`"
Les dije también que todas sus predicaciones,
bautismos y sacrificios no los santificarían,
y les pedí que miraran a Cristo en ellos y que no miraran a los hombres,
porque Cristo era el que santificaba.
Entonces corrieron a muchas palabras,
pero les dije que ellos no debían discutir acerca de Dios y de Cristo, sino obedecerlo.
El poder de Dios tronó entre ellos y volaron como paja delante
de él. Me metieron y me sacaron de la habitación varias veces,
apresurándome hacia atrás y hacia adelante;
porque me habían estado interrogando desde la primera
hora hasta la novena hora de la noche.
A veces me decían en forma de burla, que yo había sido tomado en un éxtasis.
Luego me preguntaron si yo no tenía pecado.
Les respondí: "`Cristo mi Salvador ha quitado mi pecado, y en Él no hay pecado.`"
Preguntaron cómo sabíamos que Cristo moraba en nosotros.
Les dije: "`Por Su Espíritu que Él nos ha dado.`"
Tentadoramente preguntaron si alguno de nosotros era Cristo.
Yo les respondí: "`No, nosotros no somos nada, Cristo es todo.`"
Ellos dijeron: "`Si un hombre roba, ¿no es pecado?`"
Respondí: "`Toda injusticia es pecado.`"
Y así, cuando se cansaron de interrogarme, me enviaron a mí y a otro hombre,
a la casa de corrección en Derby por seis meses, acusados de blasfemos.

[.asterism]
'''

[.emphasized]
Aunque G. Fox a menudo fue encarcelado, golpeado, calumniado y maltratado,
continuó ministrando en el poder y sabiduría de Cristo hasta su muerte en 1691,
a la edad de sesenta y seis años. Cuando estuvo en libertad,
viajó incansablemente por Inglaterra, Escocia, Irlanda, Europa, las Islas del Caribe,
y las colonias en América, predicando en la demostración del Espíritu y poder,
y volviendo a las personas de las tinieblas del pecado
y de la religión hecha por el hombre,
a la luz de Jesucristo que brilla en el corazón. Cuando estuvo confinado en prisión,
escribió una gran cantidad de cartas,
documentos y tratados para el fortalecimiento de la iglesia,
y para la instrucción de todos en el camino de la verdad.
Thomas Ellwood, amigo íntimo de Fox y editor de su diario,
dijo lo siguiente de la vida y ministerio de este hombre tan notable:

[quote]
____
"`Desde 1660 hasta el momento de su muerte, lo conocí bien, conversé con él a menudo,
lo observé mucho, lo amé cariñosamente y lo honré verdaderamente;
y por buena experiencia puedo decir, que era en verdad un hombre de mente celestial,
celoso del nombre del Señor, y que prefería el honor de Dios antes que todas las cosas.
Era valiente en el servicio de la verdad; audaz al afirmarla,
paciente al sufrir por ella, incansable al trabajar en ella,
firme en su testimonio de ella; inamovible como una roca.
Era profundo en el conocimiento divino, claro en la revelación de misterios celestiales,
sencillo y poderoso en la predicación,
ferviente en la oración. Estaba ricamente dotado de sabiduría celestial;
era rápido en el discernimiento, sano en el juicio, capaz y listo a dar,
discreto en guardar el consejo; amante de la justicia, alentador de la virtud,
la justicia, la templanza, mansedumbre, pureza, castidad, modestia, humildad,
caridad y abnegación en todo, tanto de palabra como en ejemplo.`"
____
